leancloud/ticket

- api/notify.js
- modules/App.js
- modules/GlobalNav.js
- modules/Ticket.js
- modules/notification.js
- package.json
- utils/promise.js
- webpack.config.js
做了以下几件事情：
1. 登录时/已登录时以当前 user id 登录实时通讯
2. Ticket afterSave 时为这个 Ticket(nid) 创建一个暂态的 Conversation
3. 进入某个 Ticket 页面 join 对应的 Convesation
4. Replay afterSave 时向这个 Conversation 发送一条 NewReplyNotification
UI 的更新没有在这个 PR 里实现（因为估计会改）。
> feat: 当前工单回复通知

- modules/Ticket.css
- modules/Ticket.js
- modules/UpdateTicket.js
- public/index.css
> fix: 工单详情页增加工单分类和当前负责人的信息

- modules/CustomerServiceTickets.js
- modules/Tickets.js
修复 React 打印的 Encountered two children with the same key 警告。
mongo 比较两个 Object 的时候会受 key 顺序的影响。
在
https://github.com/leancloud/ticket/commit/d7ecb6997215aa41ed4da3a970f9bf8e69090872#diff-4eab0151cec66b2872440caad75abb1cR46 这次数据订正中，
joinedCustomerServices 被添加了 name 字段。但是在之后再 addUnique 的时候 mongo 认为这两个 Object 是不同的。
> fix: 在渲染前对 joinedCustomerServices 去重

- api/oauth.js
- lib/common.js
- modules/CustomerServiceTickets.js
解决 review 工单的时候遇到的问题：
* 客服工单列表按照最后一条回复时间排序（新增标签不影响客服列表展示）
* 可以 review 两月前工单
* 工单的「上月/上月/两月前」按照工单创建时间而不是更新时间更便于 review。
> 便于工单 review 的细节修改

- README.md
It seems that omitting beginning and ending `|` in table
renders incorrectly on GitHub README.
> docs(readme): markdown formatting

- api/User.js
- lib/common.js
- modules/CustomerServiceStats.js
- modules/CustomerServiceTickets.js
- modules/Ticket.js
- modules/User.js
- modules/common.js
- modules/components/UserTag/index.css
- modules/components/UserTag/index.js
- resources/schema/_User.json
本 PR 新增了两个功能
仅在客服视角下展示用户标签。目前的标签有以下 3 种：
名称|显示为|说明
-|-|-
`new`|新用户|注册时间小于3个月的用户，前端自动添加
`early-adopter`|老用户|注册时间超过2年的用户，前端自动添加
`vip`|大用户|由客服在用户详情页面手动标注
可以在 [这里](https://ticket.sdjdd.com/) 预览下效果（要先控制台中把自己变为客服，appid: `02AXSPNhJaEqgBfHftLpIsj2-gzGzoHsz`） 。
客服手动标注的用户标签存放在 _User Class 中的 `tags` (Array) 列中。
原需求为：新增本月（本周）的新用户活跃工单统计，即新添加一个表格展示新用户的工单统计。
因新用户的统计仅是原统计表格中的一小部分数据，在原表格中将其标出可以少创建一个表格。
预览图：
请 @SXiaoXu 确认下是否可以使用这种方式实现。
> feat: user tags & mark new users in stats

- package-lock.json
- package.json
Using a fork is unnecessary since
jonschlinkert/remarkable#277 has been merged
and released in 1.7.2.
> build: use upstream version of remarkable

- api/Ticket.js
- lib/common.js
- modules/TicketStatusLabel.js
- modules/i18n/locales.js
在整理工单状态机的时候发现，「关闭工单」操作 reject 以及对应的状态 REJECTED 特别难理解。所以重命名为 close / CLOSED。
我理解 reject 是与 fulfill 相对的，但「二次确认」应该是一个可选的功能，如果不需要的话，只剩一个 reject 很不好理解。而且实际上文案都是用的「关闭」这个词，所以不如直接一点用 close / CLOSED。
状态转移如图所示： https://sketchviz.com/@leeyeh/bf19ae9be26aa29c8b16b3d4f6721556/6c3065a73860a2b2da2b726807706597cd5b4a4f
> feat(Ticket): rename status REJECTED to CLOSED

- api/oauth.js
- config.js
- lib/common.js
- modules/App.js
- modules/Login.js
- modules/NewTicket.js
- modules/Tag.js
- modules/User.js
- modules/common.js
- modules/settings/Profile.js
- modules/settings/Vacation.js
- package-lock.json
- package.json
- server.js
- 把 LeanCloud 相关的功能使用 ENABLE_LEANCLOUD_INTERGRATION 环境变量来控制。
- Avatar 组件，如果用户没有 email，使用 username 计算 hash。并且不再在 OpsLog 中冗余用户的 gravatarHash 了，除了 _User 表自带的冗余 hash，其他所有要显示头像的地方都在前端计算。
分别在 leanticket.cn 与 xd.leanticket.cn 测试了（需要客服权限的可以找我加）。
> refactor: 将 LeanCloud 相关的功能收敛为一个开关

- modules/i18n/locales.js
since it is not very easy  to tweak the Bootstrap `.container` width.
And `about` would feel lonely if we had moved it to the bottom.
> cosm(GlobalNav): simplify wording to avoid exceeding width

- api/stats.js
- config.js
- modules/NewTicket.js
- modules/StatsChart.js
- modules/StatsSummary.js
- modules/Ticket.js
- modules/components/WeekendWarning/index.js
- modules/i18n/locales.js
- server.js
Close #142
- 增加工作日的响应时间统计
- 周末提交工单时增加文字提醒，内容类似「非工作日提醒：我们会尽快回复工单，请稍等」之类的。
周末时，在创建工单页、工单详情页（用户视角）下显示：
- 活跃工单数（分类）下面所有分类的统计数量累加与总览中活跃工单总数不一致
- 有的客服名字是 undefined
- 统计页新用户标签显示在客服列表中（可能是重构时粘错了）
- 获取 offsetDays 的逻辑
- 统计页组件补充 key 属性
- 删除未使用的云函数
> feat: workday statistics

- modules/CustomerServiceTickets.js
其实这个页面在 router 层面保证了必须登录后才能查看，但登出前的一瞬间还是会触发渲染。最小化的修复方式也就是在所有直接获取 auth.currentUser() 属性的位置加个判断了吧。
> fix: logout error

- api/Ticket.js
- modules/NewTicket.js
Ticket 的 ACL 是在客户端指定的。这个 PR 把这个逻辑移到了 beforeSave hook 里。
@sdjcw 不是很确定当初这么设计是不是有什么玄机。
> fix(Ticket): ensure ACL by hook

- api/Ticket.js
改成 async 方法超时了，看来原来的逻辑并没有等所有操作执行完才返回。
> fix: operateTicket timeout

- resources/schema/Ticket.json
之前 `unreadCount` 的类型是我手写的，现在更新成 v2 版本。
感觉版本库里的 schema 和线上用的有差距啊，要不要统一一下？
> feat: update schema of Ticket class

- api/common.js
- config.js
- config.webapp.js
- lib/common.js
- modules/CustomerServiceTickets.js
- modules/OrganizationSelect.js
- modules/StatsChart.js
- modules/StatsSummary.js
- modules/Ticket/index.js
- modules/common.js
- modules/components/WeekendWarning/index.js
- modules/settings/Vacation.js
- server.js
为自定义用户、客服名称的显示方式铺路。
把 lib/common.js 中的 getUserDisplayName 挪到 api/common.js 中，目前这个方法仅后端用来在 mail / bearychat / wechat 的提醒中获取客服的名称。前端通过 /config.webapp.js 中的 userDisplayName 获取用户名称，customerServiceDisplayName 获取客服名称。
> feat: config file of webapp

- config.webapp.js
- modules/Ticket/TicketMetadata.js
- modules/Ticket/index.css
- modules/i18n/locales.js
- 新增：翻译 Tap Metadata
- 修复：长字符串换行
已部署到 ticket-xd 的预备环境。
感觉 `VID` 和 `taptapID` 重复了，`gameName` 和 `appName` 弄混了 🤔
> feat: comment of tap metadata

- modules/settings/CustomerServiceProfile.js
- server.js
xd 的工单没配 Wechat 插件，导致没有 `getWechatEnterpriseUsers` 这个云函数，进而导致客服个人配置页面报错。先临时这样修一下。
> fix(CSProfile): hide wechat form when no wechat plugin

- modules/Login.js
- modules/utils/AuthRoute.js
Close #216 
用户名密码登录后是能跳转回去的，OAuth 会丢失上下文。索性都用 localStorage 实现好了。
> feat: redirect user to original url after login

- lib/leancloud.js
国际节点没有也没必要设置 LEANCLOUD_API_HOST 环境变量，进而导致应用因使用未定义的变量而 panic 。或许应该通过 window.VAR_NAME 这种方式获取环境变量的值？
> refactor: get LEANCLOUD_API_HOST from window object

- integrations/slack/server.js
如果没有设置 Slack 邮箱的话，发送私信的步骤会抛异常，导致无法发送广播消息。
Slack 通知功能的代码完全是按照 Zulip 通知写的，但之前使用的过程中好像没有暴露出这个问题 🤔 。
我觉得发送消息这一步失败也无所谓，就不 await 了吧。目前失败了还会导致后续无法创建 Message Object 。
> refactor(slack): send messages in non-block mode

- modules/CustomerService/Tickets.js
- modules/i18n/locales.js
- package-lock.json
- package.json
> feat: Page indicator

- api/Ticket.js
- api/index.js
- api/rule/automation/action/types.js
- api/rule/automation/api.js
- api/rule/automation/automation.js
- api/rule/automation/condition/createdAt.js
- api/rule/automation/condition/fields.js
- api/rule/automation/condition/updatedAt.js
- api/rule/automation/index.js
- api/rule/condition/status.js
- api/rule/context.js
- api/rule/trigger/index.js
- modules/Settings/Rule/Automation/condition/fields/index.js
- modules/Settings/Rule/Automation/condition/index.js
- modules/Settings/Rule/Automation/index.js
- modules/Settings/Rule/Condition/fields/index.js
- modules/Settings/Rule/Condition/index.js
- modules/Settings/Rule/components/NumberInput.js
- modules/Settings/Rule/components/Select.js
- modules/Settings/Rule/components/Value.js
- modules/Settings/index.js
- resources/schema/Automation.json
Automation 和 Trigger 类似，也是由一系列「条件」和「操作」组成。不同的是 Automation 每小时执行一次。
Zendesk 最多处理 1000 条满足 Automation 条件的工单，而目前的实现是每次执行最多检测 1000 条处于开启状态的工单。
Automation 的执行由云引擎的定时任务管理，每小时 (`0 * * * *`) 执行一次 `tickAutomation` 函数。
已部署到 sdjdd-ticket 的生产环境。
> feat: automations

- api/TicketField.js
- api/index.js
- api/middleware/index.js
- resources/schema/TicketField.json
- resources/schema/TicketFieldVariant.json
工单字段的 API
see: #243 
Request:
```jsonc
{
// 不展示给用户, 只是方便管理
"title": "道具名称 for PCR",
"type": "dropdown",
"required": true,
// 必须在 variants 中提供
"defaultLocale": "zh-cn",
"variants": [
{
"title": "道具名称",
"locale": "zh-cn",
// type 为 "dropdown" 和 "multi-select" 时必须提供
"options": [
{
"title": "铁剑",
"value": "sword01"
}
]
}
]
}
```
Response:
```json
{
"id": "6081496a00fb9b138f7f1b8c"
}
```
Note:
- 分页: `?page[size]=20&page[skip]=40`
- 筛选 active: `?active=true` | `?active=false`
Response:
```json
{
"fields": [
{
"id": "6081496a00fb9b138f7f1b8c",
"title": "装备名称 for PCR",
"type": "dropdown",
"defaultLocale": "zh-cn",
"active": true,
"required": true
}
]
}
```
Response:
```json
{
"title": "装备名称 for PCR",
"type": "dropdown",
"active": true,
"required": true,
"defaultLocale": "zh-cn",
"variants": [
{ …
```
> feat(TicketField): REST API

- api/Ticket.js
- api/index.js
- api/ticket/api.js
- api/ticket/hook-handler.js
- api/ticket/utils.js
- lib/leancloud.js
- modules/NewTicket.js
把 #255 拆小。
分别用 SDK 和 REST API 创建了个工单，没发现啥问题。
---
Request:
```json
{
"title": "工单标题",
"category_id": "分类ID",
"content": "工单内容",
"organization_id": "组织ID（可选）",
"file_ids": ["已上传的文件ID"]
}
```
Response:
```json
{
"id": "工单ID"
}
```
> refactor: create ticket by REST API

- modules/Ticket/TicketOperation.js
目前只有客服可以重新打开工单。有时用户错误的关闭了工单，或者关闭了工单之后有又遇到了问题需要继续反馈，此时是会想要「重新打开」的。在引入了对「自动关闭」功能的支持后，这个需求变的更加强烈了。
GitHub issue 的逻辑是如果是用户关闭的工单用户可以重新打开，但如果是 repo owner 关闭的则用户不能打开。但 GitHub 更多的是站在开发者的角度帮助其收集与追踪问题，而工单则是帮助开发者服务客户。并且我也没有想到允许用户重新打开工单之后会有什么问题，所以就直接默认支持打开好了。
> feat: allow user to reopen tickets

- api/user/utils.js
- modules/UserLabel.js
切换到 REST API 后，由于没返回 `created_at` 导致没法再前端计算 Early / New  两个标签。
> fix(UserLabel): calculate tag by user.created_at

- modules/CustomerService/Tickets.js
- modules/components/DelayInputForm/index.js
Close #286 
DelayInputValue 组件通过 useEffect 监听 value 变更，导致每次挂载都会执行一次 onChange 回调，进而导致调用 updatePath ，清除 page 参数。
> refactor: DelayInputValue

- api/Ticket.js
- api/rule/automation/index.js
Zendesk 是最多处理 1000 个满足条件的工单，当时为了实现简单做成了最多获取 1000 个未关闭的工单来做判断。实际测试发现这个数量可能不够，就也改成和 Zendesk 一样了。
因为不想把 Automation 条件和查询条件绑到一起，就保留获取后再判断的逻辑了。之前还给 Automation 设置了个 10 分支的缓存，但一小时执行一次也不需要缓存，就把缓存也去掉了。
> refactor: process up to 1000 tickets in one automation cycle

- api/ticket/api.js
- api/ticket/model.js
- modules/Ticket/ReplyCard.js
- modules/Ticket/TicketReply.js
- modules/Ticket/index.css
- modules/Ticket/index.js
- resources/schema/Reply.json
通过给 Reply 表添加一列 `internal` 来区分普通回复和内部注释。
内部注释对用户不可见，且不会更新 Ticket 的 `latestReply` 、`status` 、`replyCount` 和 `unreadCount` ，不会触发 notification 。
为了让其他客服能实时感知到内部注释的创建，改回监听 Ticket 、Reply 和 OpsLog 这三个表的 LiveQuery ，不过以后要改 Ticket 的 ACL 的话就又要头疼了 😑
> feat: internal comment

- modules/Ticket/TicketMetadata.js
用了最简单的方式来支持 metadata 值显示的自定义。
配置示例： https://github.com/leeyeh/ticket/commit/9fed2953e8577b5b3be6a94f2816010974c4aa14
> feat: support to config metadata value renderer

- next/api/src/cache/index.ts
- next/api/src/cache/local.ts
- next/api/src/cache/redis.ts
- next/api/src/middlewares/error.ts
- next/api/src/middlewares/index.ts
- next/api/src/middlewares/search.ts
- next/api/src/middlewares/sort.ts
- next/api/src/models/category/Category.ts
- next/api/src/models/form/index.ts
- next/api/src/models/ticket/index.ts
- next/api/src/models/user/index.ts
- next/api/src/routers/category.ts
- next/api/src/routers/staff.ts
- next/api/src/routers/ticket.ts
- 返回结果去掉 `items` ，直接返回数组；通过 `X-Total-Count` 返回总数
- 添加本地缓存；在 redis 缓存的基础上，使用本地缓存缓存所有分类，TTL = 10 seconds
- 添加工单详情 API
- 添加 `GET /categories/:id/fields` 获取分类字段
> feat(next): more api

- api/category/utils.js
- api/ticket/api.js
- api/ticket/model.js
- embed/v1/package-lock.json
- embed/v1/package.json
- embed/v1/src/App/Home/index.tsx
- embed/v1/src/App/LogIn/index.tsx
- embed/v1/src/App/Tickets/New/index.tsx
- embed/v1/src/App/Tickets/Ticket/index.tsx
- embed/v1/src/App/Tickets/index.tsx
- embed/v1/src/App/index.tsx
- embed/v1/src/components/ControlButton/index.tsx
- embed/v1/src/index.tsx
- embed/v1/src/leancloud/index.ts
- embed/v1/vite.config.js
- modules/Settings/Category.js
- modules/Ticket/Category/index.js
- modules/Ticket/OpsLog.js
- modules/Ticket/TicketMetadata.js
- resources/schema/Ticket.json
- server.js
多个应用的情况下，可以使用应用作为一级分类。此时对于某个应用，应用内嵌的工单页应该看不到其他的分类。所以内嵌工单页的  baseurl 加了两级，支持指定一个分类为 root 分类。
- 工单详情页展示分类路径隐藏 root 分类（不过现在似乎并没有展示分类）
一些考虑：
- root category 是可选的，从语义化的角度放在 search 里会比较合适，但这里直接作为 basename 加到了 URL path 部分，是为了保持这部分信息在路由跳转之间保留（放在 search 里很难保证），同时让内部的路由操作完全感知不到这部分的存在。
- 同样为了保证不会不小心把无关的 category 露出，如果没有指定 root category，会明确返回 404 页面。如果开发者不需要指定 root category，则需要在 URL 里显式的使用 `-` 作为 root category 的 ID。
> feat: root category

- api/TicketForm.js
- modules/NewTicket.js
- modules/Ticket/TicketMetadata.js
统一后端处理 locale 这样其他客户端只需要传递 language 即可。
还有一种做法是客户端处理 服务端只接受合法的 locale
> fix: unify locale

- api/ticket/api.js
- in-app/v1/src/App/Tickets/Ticket/index.tsx
- modules/Ticket/index.js
- resources/schema/Reply.json
https://xindong.slack.com/archives/C01RY5JHB47/p1630553941034500
之前通过 Reply 表的 active 列判断回复是否被删除（值为 `false` 表示被删除）。获取回复时只获取 active = `true` 的行，但这样拿不到之前发布的回复（active 列为空）。
现改成通过 deletedAt 判断（和判断分类是否被删除的逻辑保持一致）。
> fix: mark reply as deleted by deletedAt

- next/api/src/model2/Category.ts
- next/api/src/model2/FAQ.ts
- next/api/src/model2/File.ts
- next/api/src/model2/Group.ts
- next/api/src/model2/Organization.ts
- next/api/src/model2/Ticket.ts
- next/api/src/model2/TicketField.ts
- next/api/src/model2/TicketForm.ts
- next/api/src/model2/User.ts
- next/api/src/orm/helpers.ts
- next/api/src/orm/index.ts
- next/api/src/orm/model.ts
- next/api/src/orm/preloader.ts
- next/api/src/orm/query.ts
- next/api/src/orm/relation.ts
- next/api/src/orm/utils.ts
- next/api/tsconfig.json
为了少写一些查询、组合数据的逻辑，基于 leancloud-storage 实现了一个 ORM 。
目前还差中间表和 AV.Relation 的关系没有实现（反向关联也都没有实现，因为我们没有用到，等用到的时候再说吧 🏃 💨 ）。先提出来让各位 review 一下，收集一些意见。
在 `/next/api/src/model2` 里添加了一些基于这个 ORM 定义的数据模型，可以先看一下这些文件。
为模型字段设置好关系类型后，就可以在查询数据时把相关联的数据加载进来。比如 Ticket 模型中有如下字段：
```ts
export class Ticket extends Model {
@field({
avObjectKey: 'category',
encode: false,
decode: (category) => category.objectId,
})
categoryId!: string;
@field({
encode: (c: Category) => ({ name: c.name, objectId: c.id }),
decode: false,
})
@belongsTo(Category)
category?: Category;
@pointerId(User)
authorId!: string;
@pointTo(User)
author?: User;
@pointerIds(File)
fileIds?: string[];
@hasManyThroughPointerArray(File)
files?: File[];
}
```
查询 ticket 时可以将 category 、author 和 files 一并查询出来，且只发送 2 次请求：
```ts
const query = Ticket.query() …
```
> feat(next): orm

- next/api/src/model2/Category.ts
- next/api/src/model2/Group.ts
- next/api/src/model2/Role.ts
- next/api/src/model2/Ticket.ts
- next/api/src/model2/TicketForm.ts
- next/api/src/orm/helpers.ts
- next/api/src/orm/model.ts
- next/api/src/orm/preloader.ts
- next/api/src/orm/relation.ts
改的过程中又发现一个问题，cjs 有循环依赖的时候，没法在加载脚本的过程中拿到这个依赖的值（值是 undefined）。所以改成通过 getter ，在使用的时候获取。
我现在明白为啥 Adonis 用 getter 定义关联模型了 😑 。
> refactor(next/api): 使用 getter 获取关联的 Model

- modules/Ticket/TicketMetadata.js
一个小改动，放开 meta data 展示时的类型限制，并确保传给自定义组件展示时是原始数据类型。
> fix: display all typed metaData

- next/api/src/model/Group.ts
- next/api/src/model/OpsLog.ts
- next/api/src/model/Reply.ts
- next/api/src/model/Ticket.ts
- next/api/src/model/User.ts
- next/api/src/orm/command.ts
- next/api/src/orm/helpers.ts
- next/api/src/orm/index.ts
- next/api/src/orm/model.ts
- next/api/src/orm/preloader.ts
- next/api/src/orm/query.ts
- next/api/src/orm/relation.ts
- next/api/src/response/ticket.ts
- next/api/src/router/ticket.ts
照搬旧版，缺少通知。
与旧版的区别：internal 为 `false` 时不将该字段写入数据库，因为最早的回复也是没有 internal 字段的，避免后续被误解为非 internal 回复的 internal 一定为 `false` 。
> feat(next/api): create reply

- next/api/src/utils/htmlify.ts
新版的 remarkable 把 linkfiy 功能拆成插件了。
> refactor(next/api): remarkable use linkify plugin

- api/stats.js
负责人改为可选后导致计算统计数据时可能出错。
```
[2021-09-26T02:11:58.018120000Z][instance:web1] err >> 60e4ffbd81c4dc47a2a61108 TypeError: Cannot read property 'id' of null
[2021-09-26T02:11:58.018187300Z][instance:web1]     at ReplyTimeStats.getCustomerServiceTime (/home/leanengine/app/api/stats.js:120:25)
[2021-09-26T02:11:58.018192600Z][instance:web1]     at ReplyTimeStats.forEachReplyOrOpsLog (/home/leanengine/app/api/stats.js:152:40)
[2021-09-26T02:11:58.018196200Z][instance:web1]     at /home/leanengine/app/api/stats.js:64:22
[2021-09-26T02:11:58.018199800Z][instance:web1]     at arrayEach (/home/leanengine/app/node_modules/lodash/lodash.js:530:11)
[2021-09-26T02:11:58.018203000Z][instance:web1]     at Function.forEach (/home/leanengine/app/node_modules/lodash/lodash.js:9410:14) …
```
> fix(stats): ticket may has no assignee

- api/Ticket.js
修改操作是异步的，立即判断工单是否被更新将始终返回 false，进而导致不会更新工单。
> fix(automation): waiting for async operation to finish

- next/api/src/integration/slack.ts
- next/package-lock.json
- next/package.json
完全复刻旧版的 Slack 通知功能。
由于 Wechat 和 Zulip 已不使用，就不复刻了，用到的时候再说。这个合完开始往 next 上迁工单的创建、更新和回复。
> feat(next): slack integration

- api/stats.js
> fix(stats): exclude internal reply

- next/api/.swcrc
- next/api/nodemon.json
- next/api/package-lock.json
- next/api/package.json
用上 #417 之后，遇到几次 `MODULE_NOT_FOUND` 的错误，觉得基于时序的编译流程还是不够完美（可能我用的机器 CPU 不行，delay 200 还是不够 👀 ）。
既然 tsc 编译速度慢，不如换个速度更快的工具。一开始打算用 esbuild，但 esbuild 编译 ts 有一些[限制](https://esbuild.github.io/content-types/#typescript-caveats)（不过不影响当前项目）。swc 没有这些限制，next.js 和 deno 都在用，就换成它了。不过只是开发的时候用它编译，减少等待时间，部署的时候还是用 tsc。
目前还是用的全量编译，编译 114 个文件用时 500ms 左右。监听改动，只编译修改的文件用时更短，但瓶颈在应用启动的速度上，编译用时几 ms 还是几百 ms 没太大区别。
> build(next): compile with swc [dev]

- api/category/utils.js
- api/ticket/model.js
Dyin 反馈 DC 侧无法提交工单，看日志判断应该是分类查询默认 limit 100 的问题，给 DC hotfix 了一下（手动设置 limit 为 1000）。
后来改 master 的时候发现不需要每次创建/更新工单时都查询全部分类。这个应该是之前打算冗余 categoryPath 到 ticket 表，但后来取消了，代码没删干净。现在改成只获取指定的分类。
> refactor: do not fetch all categories on create ticket

- in-app/v1/package-lock.json
- in-app/v1/package.json
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/CheckboxGroup/index.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/ErrorMessage.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Input/index.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/RadioGroup/index.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Select/index.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Textarea/index.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Uploader/index.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/CustomField/index.tsx
- in-app/v1/src/App/Tickets/New/CustomForm/index.module.css
- in-app/v1/src/App/Tickets/New/CustomForm/index.tsx
- in-app/v1/src/App/Tickets/New/index.tsx
- in-app/v1/src/api/category.ts
- in-app/v1/src/components/Uploader/index.tsx
- in-app/v1/src/i18n/locales/zh.json
- in-app/v1/src/leancloud/index.ts
- in-app/v1/tsconfig.json
- in-app/v1/vite.config.js
重写自定义表单和字段，现在的自定义表单是一个真正的 `<form />`。
由于 header 不再固定，ios 下 scrollIntoView 位置不准确的问题得到解决，之前的一些奇技淫巧也没有重新实现。
旧代码没删，留作参考。
---
API 用的还是 v1，单开一个 PR 升 API 版本。
> refactor(in-app): custom fields

- in-app/v1/src/App/Tickets/New/CustomForm/index.tsx
- in-app/v1/src/App/Tickets/New/index.tsx
- in-app/v1/src/App/Tickets/New/usePersistFormData.ts
把用户创建工单时临时输入的数据存到 localStorage 中，防止切换页面导致丢失已输入的数据。
> feat(in-app): persist user inputs

- in-app/v1/package-lock.json
- in-app/v1/package.json
升级 open-leancloud-storage 到 0.0.37 后无法上传文件，原因是 rollup 无法解析 open-leancloud-storage 的项目结构，导致引入了针对 node.js 平台的 storage package。但是 webpack 就没问题 🤔 
在 rollup 支持或者调整 sdk 结构之前，先继续用 0.0.35 吧，反正 0.0.35 到 0.0.37 之间也没有功能更新。
> fix(in-app): upload files

- next/api/src/response/ticket-field.ts
不再往自定义字段描述的返回值里填充空字符串。打算后续通过 API 返回内置字段（title、description），这俩本身是没有 description 的，强行返回空字符串很奇怪。
> feat(next/api): not autofill custom field description any more

- next/api/src/orm/query.ts
- next/api/src/router/ticket.ts
之前 AuthOptions 和 PreloadOptions 共用同一个 object，导致设置 onQuery / data 时不再使用 .find 的 AuthOptions 覆盖 Preloader 的 AuthOptions。现在改成使用 PreloadOptions.authOptions 存放 AuthOptions，避免上述情况。
又加了个 `?include=unreadCount` 的开关。
> fix(next/api): preloader auth options

- api/ticket/model.js
- next/api/src/model/Ticket.ts
- next/api/src/notification/index.ts
- next/api/src/ticket/TicketUpdater.ts
关闭/重新打开工单时增加 notification.unreadCount 的逻辑实现了两次。去掉间接实现。
> fix(api): increase unread count of notification twice

- next/api/src/orm/helpers.ts
- next/api/src/orm/preloader.ts
- next/api/src/orm/relation.ts
Preloader 的设计不太合理，导致重构范围比较大。先把 relation type 的修改发出来。
> refactor(next/api): model relation type

- next/api/src/model/Ticket.ts
- next/api/src/orm/helpers.ts
- next/api/src/orm/model.ts
- next/api/src/orm/preloader.ts
- next/api/src/orm/query.ts
- next/api/src/orm/relation.ts
- next/api/src/response/ticket.ts
- next/api/src/router/ticket.ts
ORM 的 Relation 依赖 Model instance 上的属性，感觉不太好，最好还是直接依赖数据库中的数据。
尝试改了一下，发现 Model instance 并不总是和已保存的 AV.Object 一一对应（比如反序列化后的 instance 就没有对应的 AV.Object），所以不好改。
目前 Relation 还是依赖部分 Model instance 上的属性，在定义 Relation 时需要保证相关的 Model 定义了 Relation 所需的属性，算是增加了定义时的负担，但提升了一点点使用上的灵活性（反序列化后的 Model 依然可以进行 load）。
这个 PR 重写了各 Relation 的定义，删除了一些 Preloader 上没使用的功能，简化了装饰器的定义。还把之前错误定义的 Ticket `hasOne` Notification 改成了 `hasManyThroughPointer`。可以只看 4e723c89a54d334ee4bf8a78ab61ab3e3fafc859 这个提交。
> feat(next/api): HasMany relation

- next/api/src/model/TicketField.ts
- next/api/src/model/TicketFieldVariant.ts
- next/api/src/model/TicketForm.ts
- next/api/src/response/ticket-field.ts
- next/api/src/router/ticket-field.ts
- next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx
- next/web/src/App/Admin/Settings/TicketFields/index.tsx
- next/web/src/App/Admin/Settings/TicketForms/index.tsx
- next/web/src/api/ticket-field.ts
- next/web/src/utils/useSearchParams.tsx
- resources/schema/TicketField.json
- resources/schema/TicketFieldVariant.json
> https://confluence.xindong.com/pages/viewpage.action?pageId=445030432
功能|子功能|描述
-|-|-
工单模板 | 工单字段可见性配置 | 支持客服对于工单字段的可见性进行配置<br />例如：<br />在用户提单的场景下，该模板中的角色ID 不需要用户填写，所以隐藏该字段。<br />但在客服提单的场景下，该模板中的角色ID 需要客服填写，所以需要显示该字段
TicketField 新增一列 `visible`，表示该字段对用户是否可见。
TicketFieldVariant 新增一列 `titleForCustomerService`，表示该字段向客服显示的标题。
新增「权限」配置项，可将设置为「仅限客服」或「用户可编辑」，对应 TicketField.visible。
新增「向客服展示的标题」配置项，对应 TicketFieldVariant.titleForCustomerService。
fix: 不再返回 active 为 `false` 的字段（close #469）
feat: 不返回 visible 为 `false` 的字段
variants 现在是一个数组。
fix: 表单配置页的取消按钮无效
feat: useSearchParam(s) 的 setter 支持 NavigateOptions（但是并没有起作用，可能是 react-router 的 bug 😑 ）
重新导入 TicketField.json，并将已有数据的 visible 设置为 `true`。
重新导入 TicketFieldVariant.json，并将已有数据的 titleForCustomerService 设置为和 title 相同。
> feat: ticket field privilege

- next/api/src/queue/index.ts
解决预备环境也会消费队列中的任务的问题。
直接禁止预备环境消费也不好，这样就不能做测试了。所以改为预备环境使用单独的队列。
> feat(next/api): queues for stage environment

- next/api/src/orm/query.ts
Query.where 方法传入的函数不用再返回一个 Query 了。
> refactor(next/api): Query.where(bunch)

- Deploy.md
- docs/api2.yml
- next/api/src/model/Article.ts
- next/api/src/model/ArticleRevision.ts
- next/api/src/response/article-revision.ts
- next/api/src/router/article.ts
- next/web/src/App/Admin/Settings/Articles/EditArticleForm.tsx
- next/web/src/App/Admin/Settings/Articles/Revision.tsx
- next/web/src/App/Admin/Settings/Articles/index.tsx
- next/web/src/App/Admin/Settings/index.tsx
- next/web/src/api/article-revision.ts
- next/web/src/api/article.ts
- resources/schema/FAQ.json
- resources/schema/FAQRevision.json
没做完，但先发出来求合（因为发现有冲突了（已解决））。
目前完成的功能是完整可用的。之后会继续做：
- Revision 改造成双向链表，支持向前向后看版本。
- Revision 增加 diff 视图
- Revision 详情页支持回滚
- 增加 FAQFeedback（评价实际关联到 Revision）。
- Article 增加 tag 属性（支持过滤）
> feat: article revision

- package-lock.json
- package.json
升级 SDK 到 v0.0.38，解决 rollup 打包时使用 node.js 平台代码的问题。
> deps: upgrade open-leancloud-storage to v0.0.38

- next/web/script/generateEnv.js
- next/web/src/global.d.ts
- next/web/src/leancloud/index.ts
之前一直用的 LC_API_SERVER（值为 `http://api.leancloud.cn`），由于没调用云函数，也没上传过文件，所以没有及时发现这个问题。
> fix(next/web): use LEANCLOUD_API_HOST as server URL

- next/api/src/config/index.ts
- next/api/src/model/User.ts
- next/api/src/router/ticket.ts
允许开发版用户提交某些分类下的工单。
在设置了 `ENABLE_LEANCLOUD_INTEGRATION` 环境变量的前提下，新增 `CATEGORIES_ALLOW_DEV_USER_SUBMIT_TICKET` 环境变量，值为分类 ID，多个 ID 请用换行符分隔。用户提交这些分类下的工单时不再判断该用户是否拥有商用版应用。
使用环境变量是因为这个功能是 LeanTicket 独有的，不想因此修改表结构。而且目前来看这样的分类不会太多，环境变量也能 hold 住。
先判断用户是否有商用版应用，没有时再判断该用户是否为客服。之前是反过来的。
客服提工单的频率远低于用户提工单的频率，多数情况下可以少请求 _User 和 _Role 表一次，降低开销 :wise-me:
> feat(next/api): allow dev tier users to submit tickets under certain categories

- next/web/package-lock.json
- next/web/package.json
- next/web/src/App/Admin/Settings/Articles/EditArticleForm.tsx
- next/web/src/App/Admin/Settings/index.tsx
- next/web/src/api/article.ts
- next/web/src/components/MarkdownEditor/index.tsx
分别对比了用 https://ui.toast.com/tui-editor 与  https://github.com/RIP21/react-simplemde-editor 实现的效果，
最终选了 tui-editor，主要原因是支持所见既所得模式（后者不仅仅是缺少该模式，包括图片上传 URL 插入这些按钮的逻辑，对非技术背景用户来说要求还是有一点点高）。虽然后者的自动保存草稿等功能非常实用，但相对来说还是比较容易自己实现的。
剩余 Todo 的事情：
- 保存草稿
- 上传图片的时候需要有个 loading 效果
> feat: MarkdownEditor

- next/api/src/config/index.ts
还是用逗号分隔吧，不然没法 `$(lean env)` 这么玩了。
> feat(next/api): use commas to split env

- api/ticketField/index.js
https://xindong.slack.com/archives/C01UB1M7BBK/p1643273821029000
不再验证 locale 参数。这东西本来也不应该限制的太严格。
目前不支持 locale 会 fallback 到默认 locale。
> feat: do not validate locale anymore

- modules/Ticket/ReplyCard.js
之前恢复了允许工单描述为空的逻辑（方便已经填写自定义字段的用户省略描述），这样没有描述就显得空空的，所以加了个占位提示。
模仿 GitHub 的效果：
> feat: empty content placeholder

- next/api/src/controller/category.ts
- next/api/src/model/Category.ts
- next/api/src/model/Ticket.ts
- next/api/src/router/ticket.ts
- next/api/src/service/category.ts
准备用 REST API 替换底层存储接口实现的分类管理。提前搞一个 category service 来做分类的 CRUD，屏蔽缓存相关的细节。
目前的功能和原 CategoryManager 相同。还去掉了本地缓存：凭我的直觉 5 秒的本地缓存没啥大用，还带来了多实例下的数据不一致，索性就不要了。
> feat(next/api): category service

- Deploy.md
- api/next-shim.js
- next/api/package-lock.json
- next/api/package.json
- next/api/src/article/stats.ts
- next/api/src/model/Article.ts
- next/api/src/model/ArticleRevision.ts
- next/api/src/model/Notification.ts
- next/api/src/model/Ticket.ts
- next/api/src/notification/index.ts
- next/api/src/orm/model.ts
- next/api/src/response/article-revision.ts
- next/api/src/response/article.ts
- next/api/src/router/article.ts
- next/web/src/App/Admin/Settings/Articles/FeedbackSummary.tsx
- next/web/src/App/Admin/Settings/Articles/Revision.tsx
- next/web/src/App/Admin/Settings/Articles/index.tsx
- next/web/src/api/article-revision.ts
- next/web/src/api/article.ts
- resources/schema/FAQ.json
- resources/schema/FAQRevision.json
最终选择了最简单可靠的方案：每小时统计一次当前上线的文章的所有反馈数量记录到当前版本数据里。（之前还考虑过记录每小时新增的反馈数量、PV、UV，这样可以看到变化趋势，但感觉这个功能可能用量不会太多还是选了简单的）。
具体的数据库变动：
- 为 Revision 增加了 upvote 与 downvote 字段
- 为 Article 增加了 revision 字段，冗余存储最近一次对内容的 revision（读优化）。
部署到了 demo 环境。
> feat(article): upvote and downvote count for revisions

- next/api/src/controller/user.ts
- next/api/src/router/ticket.ts
- next/web/src/App/Admin/Tickets/Filter/FilterForm/TagSelect.tsx
- next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
- next/web/src/App/Admin/Tickets/Filter/useTicketFilter.ts
- next/web/src/App/Admin/Tickets/TicketView/TicketList/index.tsx
- next/web/src/App/Admin/Tickets/TicketView/TicketTable/index.tsx
- next/web/src/api/ticket.ts
- next/web/src/api/user.ts
支持通过标签搜索工单。
其实本来想先做关键词搜索功能的，所以重构了下 TicketList 和 TicketTable，不再通过 include author/assignee/group 的方式获取创建者、负责人、客服组等信息，方便切换到全文搜索。但后来发现工作量比较大，就先做通过标签搜索的功能了。不过这部分也提交上来了。
堆了一些代码实现的，考虑到可能切换 codebase，就先这样吧。或者重构的时候再说 🏃
> feat(next): search tickets by tag

- next/api/src/router/ticket.ts
- next/web/src/App/Admin/Tickets/Filter/FilterForm/EvaluationStarSelect.tsx
- next/web/src/App/Admin/Tickets/Filter/FilterForm/TagSelect.tsx
- next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
- next/web/src/App/Admin/Tickets/Filter/useTicketFilter.ts
- next/web/src/App/Admin/Tickets/index.tsx
- next/web/src/api/ticket.ts
- next/web/src/api/user.ts
- next/web/src/components/common/UserSelect.tsx
支持通过关键字搜索工单。
新增 API `GET /api/2/tickets/search`，底层使用 LeanCloud 的「全文搜索」功能，支持 `GET /api/2/tickets` 的全部过滤条件的同时，还支持通过标题（title）和描述（content）中的关键词搜索工单。
前端判断过滤条件中是否包含关键词，包含则使用 `GET /api/2/tickets/search` 进行搜索，否则使用 `GET /api/2/tickets`。
不支持通过 nid 进行搜索。~~考虑到这个功能实在是太离谱了~~ 因为全文搜索只支持为 10 个字段创建索引，目前没有为 privateTags 创建索引，导致无法通过私有标签进行搜索。所以想把 nid 的索引让给 privateTags。
还不支持高亮显示关键词，这个后续再加罢 🏃 
- 支持通过创建者（authorId）搜索工单
- 支持通过评价（evaluation.star）搜索工单
旧版的关键词搜索是 @fareco 做的，有时间的话也看一眼吧 :lespect:
> feat(next): search tickets

- next/api/src/controller/category.ts
- next/web/src/App/Admin/Settings/Categories/CategoryForm.tsx
- next/web/src/App/Admin/Settings/Categories/index.tsx
- next/web/src/api/category.ts
https://xindong.slack.com/archives/C01RY5JHB47/p1646386748768599
next 前端是直接 serve 的静态文件，拿不到云引擎的环境变量，所以就先不判断用的哪种模板了，都允许配置。
> feat(next): support category template configuration

- api/Ticket.js
- api/ticket/api.js
- api/ticket/model.js
- next/api/src/model/Ticket.ts
- next/api/src/ticket/automation/condition/metaData.ts
- next/api/src/ticket/automation/context.ts
- next/api/src/ticket/automation/time-trigger/condition/index.ts
- next/api/src/ticket/automation/trigger/condition/index.ts
- next/web/src/App/Admin/Settings/Automations/TimeTriggers/conditions/index.ts
- next/web/src/App/Admin/Settings/Automations/Triggers/conditions/index.ts
- next/web/src/App/Admin/Settings/Automations/conditions/MetaData.tsx
https://xindong.slack.com/archives/C01RY5JHB47/p1646810532737339
此为第二步：增加判断 metaData 的触发器条件。
通过 lodash 的 get 方法获取 metaData 中指定 path 的数据，通过 isEqual 判断是否相等。
> feat: metaData trigger condition

- next/api/src/controller/dynamic-content.ts
- next/api/src/controller/ticket-field.ts
- next/api/src/i18n/locales.ts
- next/api/src/model/DynamicContent.ts
- next/api/src/model/DynamicContentVariant.ts
- next/api/src/response/dynamic-content-variant.ts
- next/api/src/response/dynamic-content.ts
- next/api/src/utils/template.ts
- next/web/src/App/Admin/Settings/DynamicContents/DynamicContentForm.tsx
- next/web/src/App/Admin/Settings/DynamicContents/index.tsx
- next/web/src/App/Admin/Settings/Menu.tsx
- next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx
- next/web/src/App/Admin/Settings/index.tsx
- next/web/src/api/dynamic-content.ts
- next/web/src/i18n/locales.ts
- resources/schema/DynamicContent.json
- resources/schema/DynamicContentVariant.json
重新实现 Dynamic content。
还包含一个自己 suo 的 template renderer。考虑过 mustache.js，但这个库在当前场景不够好用，而且会 escape 嵌入的值，就没有使用。
> feat(next): dynamic content management

- modules/Login.js
- modules/utils/AuthRoute.js
会导致在没有权限的时候直接抛异常白屏。
Lesson learned: 不要用 `Error` 做类名。
> fix: import the missing ErrorMessage

- next/api/src/model/Ticket.ts
> fix(api): prevernt the state change when a new ticket is replied by a user

- modules/Ticket/index.js
- modules/User.js
- modules/UserLabel.js
对于部分第三方登录方式创建的用户， username 对客服可能是有意义的（与 name 是不同的含义）。在这种情况下把 username 展示出来。
> feat(lagecy-web): display username on the ticket page

- modules/CustomerService/Tickets.js
- next/api/src/model/OpsLog.ts
- next/api/src/ticket/automation/action/changeStatus.ts
- next/api/src/ticket/automation/context.ts
- next/api/src/ticket/automation/time-trigger/action/index.ts
- next/api/src/ticket/automation/time-trigger/index.ts
- next/api/src/ticket/automation/trigger/action/index.ts
- next/web/src/App/Admin/Settings/Automations/TimeTriggers/actions/index.ts
- next/web/src/App/Admin/Settings/Automations/Triggers/actions/index.ts
- next/web/src/App/Admin/Settings/Automations/actions/ChangeStatus.tsx
- next/web/src/api/op-log.ts
客服有自动将用户长时间未回复的工单「归档」的诉求，但目前 Automation 提供的能力只有 close 一种操作。这有可能会导致给用户带来不被尊重的感觉。
- 客服端将「等待用户确认」状态视为「完成」状态，「等待用户确认」的工单也不会被 TimerAutomation 运行。
- Automation 的 actions 增加了所有的 OperationActions 作为可选项。
- 原来的 close action 保留但标记为废弃了，等手动改掉存量数据后再下掉。
> feat(Automation): support all operation actions

- modules/OrganizationSelect.js
- modules/Tickets/CategoryTreeMenu.css
- modules/Tickets/CategoryTreeMenu.js
- modules/Tickets/index.js
给用户侧的工单列表页加一个「根据分类 id 筛选工单」的功能。选择父分类会同时查找父分类和所有子分类的工单。
Class 组件改起来太费劲，就直接重写了。
预览地址：https://ticket.sdjdd.com/tickets?categoryId=61e8e8e2eb406f4e4a6ebee0
> feat: filter tickets by categoryId

- next/api/src/integration/slack-plus/index.ts
- next/api/src/integration/slack/index.ts
- next/api/src/model/Config.ts
- next/api/src/service/category.ts
https://xindong.slack.com/archives/C01RY599GNB/p1658489806134599
实现方式就是添加一个新的 Slack integration 的配置 object，格式是：
```ts
interface SlackConfig {
token: string;
channel?: string;
categoryChannels: Record<string, string[]>;
}
```
其中 token 和 channel 还是会 fallback 到环境变量。
categoryChannels 就是以 categoryId 为 key，channels 数组为 value 的新配置项，每次广播消息的同时还会发送消息到指定的 channels。
> feat(next/api): [Slack] sub notification by category

- in-app/v1/vite.config.js
Context: https://xindong.slack.com/archives/C01RY5JHB47/p1659673527401159
用的 core js 3 提供的 polyfill。编译完看了眼 `polyfills-legacy.{hash}.js` 确实多了 globalThis。
> feat(in-app): globalThis polyfill

- Deploy.md
- next/api/src/cloud/ticketLog/index.ts
- next/api/src/model/TicketLog.ts
- next/api/src/orm/clickhouse.ts
- next/api/src/router/ticket-stats.ts
1. 调整同步函数 如果同步数据过多则转为异步执行（考虑到独立部署基本只会运行一次，所以不在存储建立 class 而是直接看云引擎日志）
2. 移除视图 `TicketLog_latest`, 使用视图的本意是认为会有性能提升。但是不能提升不如直接移除。(也减少部署步骤)
3. privateTags 默认为 []。实际统计查询中有这个字段条件，防止 privateTags 全部都是 undefined 造成 数据仓库不创建此字段影响查询 所以默认为  []
考虑到同步会有大量读写 准备晚上工单使用频率下来后 同步下 ticket-dc 和 ticket-xd
> fix:  adjust ticket log sync

- next/web/src/App/Admin/Settings/TicketForms/index.tsx
- next/web/src/App/Admin/Tickets/Filter/FilterForm/CreatedAtSelect.tsx
- next/web/src/App/Admin/Tickets/TicketView/TicketList/index.tsx
- next/web/src/App/Admin/Tickets/TicketView/TicketTable/index.tsx
- next/web/src/App/Admin/Tickets/TicketView/index.tsx
- next/web/src/App/Admin/Tickets/index.tsx
- next/web/src/App/index.tsx
- next/web/src/components/common/LoadingCover.tsx
- next/web/src/components/common/index.ts
https://xindong.slack.com/archives/C01RY5JHB47/p1662103171373349
createdAt 筛选条件支持设置具体时间。
将 antd 的语言设置为 zh-cn。
顺手优化了下工单列表和表格的 Loading 样式。
> feat(next/web): show time in createdAt range picker

- next/api/package-lock.json
- next/api/package.json
- next/api/src/integration/mailgun.ts
- next/api/src/notification/index.ts
- next/api/src/router/ticket.ts
- next/api/src/ticket/export/ExportFileManager.ts
- next/api/src/ticket/export/ExportTicket.ts
- next/api/src/ticket/export/index.ts
- next/api/src/ticket/index.ts
- next/web/src/App/Admin/Tickets/Topbar/Exporter.tsx
- next/web/src/App/Admin/Tickets/Topbar/index.tsx
- next/web/src/api/ticket.ts
根据工单导出工单数据具体导出数据流程：
查询数据 -> 写入临时文件 -> 上传到 AV.File -> 删除临时文件  -> 发送通知邮件
导出速度：
目前 2W 条工单数据导出时间（云引擎上是 3分多，本地为 8 - 9 分）耗时主要是网络 IO 以及写入
1. 网络IO 
目前一次查询 20个工单如果想要更快可以考虑适当提升 limit 数量。（注意使用内存 本质这是空间换时间的做法）
2. 写入
写入这方面可以考虑换成 stream，另外避免每次写入创建 handle。（理论上提升不大  主要瓶颈也不再这里）
导出的工单（一个工单）数据结构为：
```ts
{
id: string;
nid: number;
title: string;
status: number;
assignee: {
id?: string;
username?: string;
nickname?: string;
email?: string;
};
author: {
id?: string;
username?: string;
nickname?: string;
};
category: {
id: string;
name: string;
description?: string;
meta?: Record<string, any>;
};
content: string;
evaluation: {
star?: number;
content?: string;
};
firstCustomerServiceReplyAt: string;
latestCustomerServiceReplyAt: string;
group: {
id?: string;
name?: string;
description?: string;
};
metaData?: …
```
> feat(next): ticket export 

- next/api/src/utils/textFilter.ts
修复了当文本过滤返回的hit_words有重合时返回的字符串与预期不符的问题
> fix(next/api): fix wrong output when hit words have overlap

- Deploy.md
- next/api/src/orm/clickhouse.ts
- next/api/src/response/ticket-stats.ts
- next/api/src/router/ticket-stats.ts
- next/api/src/router/ticket.ts
- next/web/src/App/Admin/Stats/StatsDetails.tsx
- next/web/src/App/Admin/Stats/StatsPage.tsx
- next/web/src/api/ticket-stats.ts
- next/web/src/components/Chart/index.tsx
增加评价统计
`evaluation` 字段内新增 `selections` 字段，用于传评价的选项，类型为字符串数组
```typescript
interface TicketStats {
closed: number;
conversion: number;
created: number;
externalConversion: number;
internalConversion: number;
internalReplyCount: number;
reopened: number;
firstReplyCount: number;
firstReplyTime: number;
replyTime: number;
replyTimeCount: number;
replyCount: number;
naturalReplyTime: number;
naturalReplyCount: number;
likeCount: number;  // 新增，好评数量
dislikeCount: number;  // 新增，差评数量
likeRate: number; // 新增，好评率
dislikeRate: number; // 新增，差评率
}
```
- fields: 增加 likeCount 和 dislikeCount 分别表示好评和差评
```typescript
type TicketFieldStat = Partial<Omit<TicketStats, 'likeRate' | 'dislikeRate'>> & {  // 好评率和差评率不在此 API 出现
date?: Date;  // 变为可选，不在 fields 传 likeCount 或 dislikeCount 时出现
selection?: string; …
```
> feat(next): impl stats for evaluation

- in-app/v1/src/App/Categories/index.module.css
- in-app/v1/src/App/Categories/index.tsx
- in-app/v1/src/App/Home/TicketsLink.tsx
- in-app/v1/src/App/Home/Topics.tsx
- in-app/v1/src/App/Home/index.module.css
- in-app/v1/src/App/Home/index.tsx
- in-app/v1/src/App/TopCategories/index.tsx
- in-app/v1/src/App/context/index.tsx
- in-app/v1/src/App/index.tsx
- in-app/v1/src/api/category.ts
- in-app/v1/src/i18n/locales/zh.json
首页展示「常见问题」模块。
目前的展示逻辑调整为：
1. 已配置 topics  首页直接展示为「常见问题」模块，通过 「提交反馈按钮」跳转到一级问题分类页面 [示例](https://stg-ticket.sdjdd.com/in-app/v1/categories/6108e403928aa97734554ef0/#anonymous-id=test-user)
2. 未配置 topics，首页直接展示一级分类 [示例](https://stg-ticket.sdjdd.com/in-app/v1/categories/61e8e8e2eb406f4e4a6ebee0/#anonymous-id=test-user)
> feat: topics

- in-app/v1/src/App/Categories/index.tsx
- in-app/v1/src/App/Home/TicketsLink.tsx
- in-app/v1/src/App/Home/index.tsx
- in-app/v1/src/App/Tickets/New/index.tsx
- in-app/v1/src/App/Tickets/index.tsx
- in-app/v1/src/App/TopCategories/index.tsx
- in-app/v1/src/App/index.tsx
- in-app/v1/src/api/category.ts
- in-app/v1/src/index.tsx
- in-app/v1/src/leancloud/index.ts
- in-app/v1/src/states/root-category.ts
- in-app/v1/src/types/index.ts
- next/api/src/controller/category.ts
完善 root  category 机制，保证仅在使用合法的 root category id 的情况下才加载子组件。
获取 root category 成功后，后续请求会携带 `x-product`（就是 root category id） header。
允许终端用户获取某一个 category。
> feat(in-app): x-root-category

- next/api/src/integration/slack/index.ts
支持配置 slack 通知事件，用于满足 tap 客服的需求(?)
ctx: https://xindong.slack.com/archives/C01EN4GRJQP/p1670497456339259?thread_ts=1669689238.483499&cid=C01EN4GRJQP
> feat(next/api): [Slack] notification event config

- in-app/v1/src/App/index.tsx
- modules/Login.js
- modules/i18n/locales/en.json
- modules/i18n/locales/zh.json
- next/api/package-lock.json
- next/api/package.json
- next/api/src/controller/user.ts
- next/api/src/model/User.ts
- oauth/lc.js
- oauth/xd-cas.js
重构了登录和注册逻辑，现在会走一遍后端获取 sessionToken 再登录而不是在前端调用 lc sdk 直接用户密码/匿名 id 登录注册
OAuth 未测试
> refactor: login and sign up

- api/next-shim.js
- next/api/src/controller/customer-service.ts
- next/api/src/model/User.ts
- next/api/src/response/user.ts
- next/api/src/router/ticket.ts
- next/api/src/ticket/TicketCreator.ts
- resources/schema/_User.json
See: https://xindong.slack.com/archives/C01RY5JHB47/p1673927589344479
简单来说就是踩了数据存储默认值的坑。没有选择处理旧数据是因为这个数据量可能很大，还会使部署操作会变得复杂。
现改为用 `inactive` 属性表示用户/客服是否被禁用，同时仅将值设置为 `undefined | true`，避免依赖默认值。
> feat(next/api): use inactive represent user activation

- next/api/src/integration/slack-plus/index.ts
给 slack-plus 添加了禁用的配置，可以手动实例化发消息但是不会被通知系统触发
> feat(next/api): slack plus can be disabled via config

- next/api/src/middleware/auth.ts
- next/api/src/model/User.ts
还挺隐蔽的一个 bug，X-Credential 分支下 findByUsername 得到的 User 没有 sessinToken，然后继续走到 /unread 的逻辑里也不会报错，只是会以未登录的状态请求然后返回一个错的结果。
> fix(api): ensure session token for ctx.currentUser attached by the auth middleware

- .npmrc
- leanengine.yaml
- package-lock.json
- package.json
突然发现一直用的 node 14 + npm 6，然而所有的 lockfile 都升到版本 2 了，应该用 npm 7+ 安装依赖。
所以升到 node 16。
> feat: node 16

- api/ticket/model.js
我记得 ACL 是不支持黑名单的，所以 `role:staff: {"read": false}` 没啥效果。
> fix: ACL of private ticket

- next/api/src/controller/dynamic-content.ts
- next/api/src/dynamic-content/dynamic-content.service.ts
- next/web/src/App/Admin/Settings/DynamicContents/index.tsx
在创建、更新、删除动态内容和其翻译文本时清除缓存。因为有了清除机制，适当延长缓存时间。
还修了一个前端表单数据不同步的 bug。
> feat(next/api): autoclear dynamic content cache

- resources/schema/_User.json
将 permissions 格式从字符串改成数组，避免一些潜在的问题。
导入 _User.json，将字符串格式的 permissions 改为数组格式。
> refactor: _User schema

- api/next-shim.js
- next/api/src/model/User.ts
- next/api/src/orm/model.ts
TDSUser identify 现在是放在 authData 里的，想要直接放到 username  里。原因有：
- 客服创建用户的时候目前只支持指定 username 创建的，放在 authData 里现在没发预创建。
- 方便展示（当然这不是主要理由，因为 name 也可以用来展示）
- User 的公开 create 权限已经关闭，不会有被绕过的风险。
> refactor: store TDSUser identify in username

- in-app/v1/src/i18n/index.ts
[i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector) 会把 order 里所有的结果拼起来...然后如果 `querystring` 传进去是 `ja-JP` 但是用户浏览器 `navigator` 有 `en` 就会把这两个拼起来变成 `['ja-JP', 'en']` 传入 i18next 的 `LanguageUtils.getBestMatchFromCodes`，然后这函数第一轮是直接 `supportedLngs` 里去找有没有一样的（用的 `indexOf`），于是匹配上 `en`（`ja-JP` 匹配 `ja` 在第二轮进行），炸了
i18next 坑真多...
> fix: in-app better i18n fallback

- next/api/package-lock.json
- next/api/package.json
- next/api/src/index.ts
v1 API 本来是支持正则的但看了一下实际没有用到，而且感觉有点太灵活了（虽然并非用户输入所以问题也不大）。v2 这里直接找了个最常用的支持通配符的 match 库。
> feat(next-api): allow wildcards in CORS_ORIGIN

- next/api/src/article/article.service.ts
- next/api/src/article/types.ts
- next/api/src/controller/category.ts
- next/api/src/model/Article.ts
- next/api/src/model/ArticleTopic.ts
- next/api/src/model/ArticleTranslation.ts
- next/api/src/response/article.ts
- next/api/src/router/article.ts
- 文章和文章翻译使用中央缓存，并在更新、删除时主动失效
- 完善文章和文章翻译的软删除逻辑
- 未发布的文章也可以通过 `/articles/:id` 访问
> feat(next/api): article centralized cache

- next/api/src/controller/customer-service.ts
改成了 `User.isCustomerService`
返回 400 感觉还是留着？不然前端交互就会有点奇怪
> refactor(api): refactor create cs

- next/api/src/controller/category.ts
- next/api/src/router/article.ts
- next/web/src/App/Tickets/New/TicketForm/index.tsx
- next/web/src/api/article.ts
自用前端改成使用 `/categories/:id/faqs` 获取常见问题。然后就没地方用 `/articles/detail` 了，移除。
另外 `/categories/:id/faqs` 和 `/categories/:id/notices` 现在也会返回内容。
> feat(next): remove article detail api

- next/api/src/ticket/export/ExportFileManager.ts
- next/api/src/ticket/export/ExportTicket.ts
- next/api/src/ticket/export/index.ts
因为 CSV 一行最后如果全部是空值，是可以全部省略的。所以思路是：
固定字段在前，维护一个 fieldKeys，后面发现新的 field 加到这个列表中然后通过指定 key 的方式生成新的一行。最后读完一遍再在文件最上面插入表头。这样只需要一次遍历即可。
> feat(export): flatten fields

- next/api/src/router/ticket.ts
修复了当以工单选项字段值筛选时，`X-Total-Count` 只会返回 `pageSize` 的问题
> fix(next/api): fix x-total-count always return pageSize when search with ticket field value

- next/web/src/App/Admin/Tickets/Ticket/TagForm.tsx
- next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
- next/web/src/App/Admin/Tickets/Ticket/api1.tsx
- next/web/src/App/Admin/Tickets/Ticket/components/CustomFields.tsx
- next/web/src/api/category.ts
- next/web/src/api/ticket.ts
实现了自定义字段的展示与编辑。
暂不支持修改文件字段，因为修改文件字段值的情况非常少，目前的实现混用了两版 API，非常恶心。等详情页迁完，开始迁 API 的时候再好好实现一下罢。
> feat(next/web): ticket detail page stage 3

- next/web/src/App/Admin/components/LocaleSelect.tsx
> fix(next/web): fix locale select emit onchange with empty array

- next/web/src/leancloud/index.ts
Recoil 会递归 Object.freeze 默认值，导致 auth.currentUser.app.payload 被 freeze，进而导致无法使用 live-query 模块（需要修改 app.payload）。
改进：不直接使用 auth.currentUser 作为 currentUserState 的默认值。
> refactor(next/web): current user state

- next/api/src/router/ticket-stats.ts
因为有权限调整了所以把统计页改成客服权限
也可以每次请求都判断客服有没有权限，有点没必要？
> fix(next/api): change stats api to customer service only

- next/api/src/common/http/error.ts
- next/api/src/common/http/index.ts
- next/api/src/router/index.ts
支持为 controller 配置一个已有的 router。
```ts
@Controller({
path: 'test',
router: new Router(),
})
export class TestController {}
```
方便逐个 endpoint 将 router 风格的代码重构为 controller。
> feat(next/api): router derived controller

- in-app/v1/src/App/Articles/index.tsx
- next/web/src/App/Admin/Settings/Articles/ArticleDetail.tsx
- next/web/src/App/Admin/Settings/Articles/components/PreviewLink.tsx
- next/web/src/App/Admin/components/LocaleModal.tsx
in-app 使用的 API 无法获取未发布的文章。为了可以预览未发布的文章，在 in-app 中提供一个特殊的文章预览页，从 localStorage 中读取文章数据。客服后台点击预览按钮后先将文章内容写入 localStorage 中，然后跳转到 in-app。
> feat(next/web): preview local article

- modules/Ticket/RecentTickets.js
- modules/Ticket/TicketMetadata.js
- next/api/src/controller/ticket.ts
- next/api/src/model/Ticket.ts
- next/api/src/response/ticket.ts
- next/api/src/router/index.ts
- next/api/src/router/ticket.ts
- next/api/src/ticket/TicketUpdater.ts
`PATCH /tickets/:id` 承载了太多的功能，所以想把关联工单的功能切出来。
改用以下几个 API 处理关联工单的功能：
获取关联工单列表（不包括自己）。
关联 id 和 ticketId 指向的工单。
将 associatedTicketId 指向的工单从 id 指向的工单的组中移除出去。
> feat: new associate ticket endpoint

- next/api/scripts/set-reply-edited-flag.js
- next/api/src/model/Reply.ts
- next/api/src/response/reply.ts
- next/api/src/router/reply.ts
- resources/schema/Reply.json
因为新版详情页里会展示被删除的回复，用 createdAt == updatedAt 判断回复是否被修改过就不准确了。所以给回复添加一个 edited 标志记录内容是否被修改过。
导入 Reply.json，创建 edited 列。
部署完成后运行 next/api/scripts/set-reply-edited-flag.js，根据提示完成对存量数据的迁移。
> feat(next/api): reply.edited flag

- in-app/v1/src/App/Home/index.tsx
- next/web/src/App/Admin/Settings/Categories/CategoryForm.tsx
把分类表单内的 isRootCategory 变成了 isProduct 因为当前设计内 product 作为入口可以不是根分类
同时将 AI 分类的展现条件进行修改，当 product 没有配置 topics 也会展示，但是作为没有开启 AI 分类时的 fallback，还是和以前一样在配置了 topics 的时候展示
> fix: category form content hidden and feedback condition

- next/api/src/service/openai.ts
- next/web/src/App/Admin/Settings/Categories/CategoryForm.tsx
考虑到某些环境下面 product 的子分类还有需要被分类到的 product，给不是根分类的 product 添加了 ai 分类描述
同时把 hidden 的分类从 prompt 里去掉
> perf(next): ai desc input show on product which is not root

- next/api/src/integration/taptap-dw/index.ts
- next/api/src/notification/index.ts
- next/api/src/ticket/automation/trigger/index.ts
任务失败后从 redis 中删除。现在只能手动重试，没有留着的必要。
> feat(next/api): remove failed jobs

- next/api/src/model/Ticket.ts
- next/api/src/orm/clickhouse.ts
- next/api/src/router/ticket-stats.ts
- next/api/src/router/ticket.ts
- next/api/src/ticket/export/ExportTicket.ts
- next/api/src/utils/yup.ts
- next/web/src/App/Admin/Tickets/Filter/FilterForm/PresetRangePicker.tsx
- next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
- next/web/src/App/Admin/Tickets/Filter/useTicketFilter.tsx
- next/web/src/api/ticket.ts
> feat: find tickets by evaluation create time

- next/web/src/App/helpers/lazy.tsx
- next/web/src/App/index.tsx
> feat(next/web): auto reload when dynamic import failed

- next/api/src/response/ticket.ts
- next/api/src/router/ticket.ts
- next/api/src/ticket/TicketUpdater.ts
- next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
- next/web/src/App/Admin/Tickets/Ticket/Timeline/index.tsx
- next/web/src/App/Admin/Tickets/Ticket/components/ReplyCard.tsx
- next/web/src/App/Admin/Tickets/Ticket/components/TicketCard.tsx
- next/web/src/App/Admin/Tickets/Ticket/mixed-ticket.tsx
- next/web/src/api/ticket.ts
> feat(next): update ticket title and content

- next/api/src/controller/customer-service.ts
- next/api/src/controller/merge-user-task.ts
- next/api/src/model/MergeUserTask.ts
- next/api/src/queue/index.ts
- next/api/src/response/merge-user-task.ts
- next/api/src/service/ticket.ts
- next/api/src/user/services/user.ts
- next/web/src/App/Admin/Settings/Users/MergeUser/components/MergeUserForm.tsx
- next/web/src/App/Admin/Settings/Users/MergeUser/index.tsx
- next/web/src/App/Admin/Settings/index.tsx
- next/web/src/api/user.ts
- resources/schema/MergeUserTask.json
将用户 A 合并到用户 B 将执行以下操作
- 禁用用户 A
- 将用户 A 的 authData 和 email 属性写入用户 B
- 将用户 A 名下的工单转移至用户 B 名下
为避免冲突，用户 A 和用户 B 不能同时存有 authData 或 email。
> feat: merge user
