leancloud/ticket

modules/Tickets.js

这是用户侧的工单列表优化
目前的问题是读取不到提交者的信息，见下图：
正常情况下应该是类似这样（客服侧视角）：
特开 PR 求助一下

wip(tieckts): update basic appearance

---

modules/Ticket.js
modules/settings/Categories.js

代码高亮解决方法出处：https://github.com/leizongmin/js-xss/issues/72

分类新增成功后清空输入框 && 修复代码高亮问题

---

api/bearychat.js
api/mail.js
api/notify.js
api/wechat.js

feat: remind customer service agents to reply ticket

---

modules/App.js
modules/NewTicket.js
package-lock.json
package.json
public/css/docsearch-override.css
server.js

在「新建工单」页面，用户输入标题时，对标题文字，通过 algolia 执行文档检索，返回关联的文档结果。

[feat] add algolia search

---

modules/CustomerServiceTickets.css
modules/CustomerServiceTickets.js
modules/Tickets.js

fb07ca54c770218df731cbcedcd0dc94f5a1e5f8 改变了工单列表项的 HTML 结构

fix: 工单列表样式微调

---

package.json
webpack.config.js

fix: 默认启用 uglify

---

modules/Ticket.js

使用「稍后回复」时，不顺带发送编辑中的草稿

---

modules/Ticket.js

feat: commitReplySoon should not post draft (#73)

---

api/oauth.js

华东的 sudo 地址错误修正，上下文在[这里](https://leanticket.cn/tickets/21850)。

update sudo url again

---

.prettierrc.yaml
api/stats.js
lib/common.js
modules/CustomerServiceStats.js
modules/CustomerServiceStats/User.js
modules/GlobalNav.js
modules/Login.js
modules/common.js
modules/routes.js
server.js

Revert "更新工单的统计页面"

---

.prettierrc.yaml
lib/common.js
modules/GlobalNav.js
modules/Login.js
modules/common.js
modules/routes.js
server.js

Revert "Merge branch 'leancloud' into develop"

---

api/stats.js
modules/CustomerServiceStats.js
modules/CustomerServiceStats/User.js

统计页面「平均首次响应和平均响应」时间改成统计本周新增工单的「平均首次响应和平均响应」时间。

modify response time

---

modules/CategoriesSelect.js
modules/settings/Category.js

fix: import path of CategoriesSelect

---

lib/leancloud.js
modules/App.js
modules/CustomerSearch.js
modules/CustomerServiceStats.js
modules/CustomerServiceTickets.js
modules/Messages.js
modules/Subscriptions.js
modules/Ticket.js
modules/Tickets.js
modules/common.js
modules/settings/Category.js
modules/settings/Organization.js
modules/settings/Vacation.js
package-lock.json
package.json

1. 通过 package.json 的 browser 字段自动选择设置了 Adapters 的 bundle ，不再需要手动设置 Adapters；
2. 移除 Database#query 方法，将 Query 相关的方法转移到 Class 上；
3. Query 改为不可变。若使用变量保存 Query ，添加查询约束时需要重新赋值；
4. 移除 Class#get 方法。

refactor: upgrade open-leancloud-storage to v0.0.4

---

modules/i18n/locales.js
modules/settings/Category.js

feat(Category): description

---

modules/NewTicket.js
modules/TicketReply.js
modules/components/TextareaWithPreview/index.js
modules/settings/FAQ.js

本想是给编辑 FAQ 的输入框加 paste 支持的，结果重构了一下就自动支持了。

refactor: move paste image to upload feature to TextareaWithPreview

---

api/common.js
lib/common.js
modules/TicketReply.js
modules/common.js
modules/routes.js

主要是给升级 webpack 铺路，1.x 的 webpack 支持混用 cjs 和 esModule 的语法，5.x 不支持了。

refactor: convert hybrid module to esModule

---

api/file.js
api/index.js

feat: file redirection

---

lib/common.js
modules/Subscriptions.js
modules/Ticket.js

Close #168
Close #173
查询关注的工单时未包含 author 和 assignee 应该是个早就存在的问题，直到修改了 gravater hash 的计算方式才暴露出来。

fix: include author and assignee when query watched tickets

---

modules/Tag.js

之前没有翻译用户视角下的 Tag key ，顺手重构了一下（格式、新 SDK 的使用风格）。

fix: translate ticket tag key

---

modules/CustomerServiceTickets.js
modules/settings/Tag.js

feat: order tickets by latestReply.updatedAt and updatedAt

---

modules/About.js
modules/CustomerServiceStats.js
modules/CustomerServiceStats/User.js
modules/CustomerServiceTickets.js
modules/NewTicket.js
modules/NotFound.js
modules/Ticket/index.js
modules/Tickets/index.js
modules/utils/DocumentTitle.js
modules/utils/hooks.js
package-lock.json
package.json

设置标题个人倾向于使用 hook 。重构其他组件之前先用 /modules/utils/DocumentTitle 代替。

refactor: remove react-document-title

---

modules/Tickets/TicketItem.js

之前重构 UserLabel 的时候把工单创建时间的格式弄坏了，修复一下。

fix(UserLabel): text format

---

modules/Ticket/index.js

https://zulip.lcops.cn/#narrow/stream/36-frontend-support/topic/.E6.96.B0.E7.89.88.E6.8E.A7.E5.88.B6.E5.8F.B0/near/2577580
xd 分支先 pick 一下？因为 master 上有好多未充分测试的改动。

feat: display self-committed reply immediately

---

modules/App.js

Error 组件覆盖了 Error 构造函数，导致通知颜色不对。

fix: rename component Error to ErrorPage

---

api/Ticket.js
lib/common.js
modules/CustomerServiceTickets.js
modules/Ticket/index.js

Close #204
已部署到 [sdjdd-ticket](https://ticket.sdjdd.com/tickets)

feat: close tickets in batch

---

config.js
integrations/slack/message.js
integrations/slack/server.js
lib/common.js
package-lock.json
package.json

Close #203 
Close #209 
暂未实现橙色状态（研发处理中），这部分可能要等到 Jira 集成做完才能实现。

feat: slack notification

---

api/Reply.js
api/Ticket.js
resources/schema/Webhook.json
server.js
webhook/index.js

feat: webhooks

---

api/stats.js

用这个逻辑重新生成了一遍 StatsTicket ，现在 lyw_leancloud 又是第一名拉 👀

fix(stats): exclude reopen log created by user

---

integrations/slack/server.js
modules/CustomerServiceTickets.js
modules/Ticket/index.js

refactor: replace reject action with close

---

api/Ticket.js
integrations/mailgun/server.js
modules/NewTicket.js
server.js

fix: mail notification & create org ticket

---

modules/Login.js
modules/utils/AuthRoute.js

refactor: prefer sessionStorage

---

api/common.js
config.webapp.js
lib/common.js
modules/CustomerServiceTickets.js
modules/OrganizationSelect.js
modules/StatsChart.js
modules/StatsSummary.js
modules/Ticket/TicketMetadata.js
modules/UserLabel.js
modules/components/WeekendWarning/index.js
modules/config/index.js
modules/settings/Vacation.js

提供一种更~易于使用~集中的客户端配置机制。增加了一个 Custom Element 挂载点。

feat: client side configuration

---

modules/NewTicket.js

feat: remove jquery

---

modules/CustomerService/Tickets.js

fix: reset page when filter changed

---

api/index.js
config.js
package-lock.json
package.json

feat: REST API support CORS

---

api/ticket/api.js
resources/schema/Reply.json

自用的 ticket 和新创建的几个应用，Reply Class 的权限作了修改，但没改 schema 。

fix: create reply object by logged-in user

---

modules/About.js
modules/CustomerService/Tickets.js
modules/NotFound.js
modules/utils/DocumentTitle.js
modules/utils/hooks.js
package-lock.json
package.json

feat: use react-use

---

api/middleware/index.js
api/ticket/api.js

- 支持查询没有 evaluation 的工单
- 支持查询 string 类型的 metadata.*
- 返回 content

feat: more conditions for query tickets

---

api/ticket/api.js

移除 metadata 相关的查询条件。
想了下，提供半个功能还不如不提供...

refactor: remove metadata support from tickets API

---

api/category/utils.js
modules/Settings/Category.js
resources/schema/Category.json

fix(Category): rename faqs -> FAQs

---

api/ticket/api.js
modules/Ticket/index.js
modules/i18n/index.js

解决几个问题：
- 客服关注工单时会更新工单 updatedAt
- 误报 Fetch ticket error
- 中文环境下 moment last week 的显示

fix: fixing and promotion

---

modules/Ticket/TicketReply.js

fix: prevent to commit empty reply

---

integrations/wechat/server.js

Wechat token 只增不减 ![image](https://user-images.githubusercontent.com/33412425/120457264-e3f08b80-c3c8-11eb-9852-100b096080c8.png)

fix(wechat): delete expired tokens before creating

---

api/category/utils.js
api/ticket/api.js

https://xindong.slack.com/archives/C01UB1M7BBK/p1623314685011900

refactor: disable category cache

---

api/file/api.js
api/index.js
api/quick-reply/api.js
lib/leancloud.js
modules/Settings/QuickReply/Add.js
modules/Settings/QuickReply/Edit.js
modules/Settings/QuickReply/index.js
modules/Settings/QuickReply/index.module.scss
modules/Settings/index.js
modules/Ticket/CSReplyEditor/QuickReplySelector.js
modules/Ticket/CSReplyEditor/index.js
modules/Ticket/CSReplyEditor/index.module.scss
modules/Ticket/TicketReply.js
modules/Ticket/index.js
modules/components/MarkdownEditor/index.js
modules/components/MarkdownEditor/index.module.scss
modules/components/Uploader/index.js
modules/components/Uploader/index.module.scss
modules/style/_custom.scss
modules/utils/useAutoSave.js
modules/utils/useUploader.js
package-lock.json
package.json
resources/schema/QuickReply.json
webpack.config.js

本来以为是个简单的功能，后来发现还要设置附件 👀 
新建一个 Class `QuickReply` 来保存快捷回复。
通过 `owner` 列区分快捷回复的权限：
- 没有 `owner` 的即为面向所有客服的快捷回复
- 有 `owner` 的快捷回复仅属于 `owner` 对应的客服
等客服组功能稳定后，可以添加一列 `group` 表示所属的客服组。
没有做严格的权限限制，只是不向客服展示不属于自己的快捷回复。
---
大部分改动都是前端组件，核心代码很少。

feat: quick reply

---

embed/v1/package.json
embed/v1/script/build.js
leanengine.yaml
package.json

想试一下 afterBuild ，但我看云引擎 wiki 里给它划掉了，就还用 postinstall 吧。

build: build embed pages at build phase

---

index.js
lib/leancloud.js

fix: remove devtool & add http headers

---

api/TicketField.js
api/TicketForm.js
modules/Settings/TicketField/Field.js
modules/Settings/TicketForm/FormPage.js
modules/Settings/TicketForm/index.js

fix: form api style

---

next/api/src/middlewares/auth.ts
next/api/src/middlewares/error.ts
next/api/src/models/group/index.ts
next/api/src/models/user/index.ts
next/api/src/routers/index.ts
next/api/src/routers/staff.ts
next/api/tsconfig.json
next/package-lock.json
next/package.json
next/web/index.html
next/web/postcss.config.js
next/web/src/App/Admin/Tickets/Filter/index.module.css
next/web/src/App/Admin/Tickets/Filter/index.tsx
next/web/src/App/Admin/Tickets/TicketItem/index.tsx
next/web/src/App/Admin/Tickets/TicketStatus/index.tsx
next/web/src/App/Admin/Tickets/api.ts
next/web/src/App/Admin/Tickets/index.tsx
next/web/src/App/Admin/index.tsx
next/web/src/App/index.tsx
next/web/src/global.d.ts
next/web/src/index.css
next/web/src/index.tsx
next/web/src/leancloud/index.tsx
next/web/src/utils/useSearchParams.ts
next/web/tailwind.config.js
next/web/tsconfig.json
next/web/vite.config.js
package-lock.json
package.json

为了方便实现「视图」开了这个新坑。因为内嵌页面的优先级比这个高，再加上这个的改动已经够大了，就先提出来。目前完成了工单列表和分页。
界面是抄的 freshdesk ，个人感觉比 zendesk 好看。
顺手升了下 open-leancloud-storage 的版本。

feat: next web app

---

in-app/v1/src/App/Tickets/New/Form/Field/Uploader/index.tsx
in-app/v1/src/App/Tickets/New/index.tsx
in-app/v1/src/leancloud/index.ts

https://xindong.slack.com/archives/D01MBJBH8AC/p1626942761000200

fix(in-app): submit request body

---

server.js

fix: set proxy middleware first

---

in-app/v1/src/leancloud/index.ts

对最终用户应该没有影响。解决调试时（忘了开隐私模式的话）In-app 登录之后覆盖掉客服登录状态的问题。

fix(in-app): do not persist user

---

docs/api1.yml
package-lock.json
package.json
server.js

先把可能会用到的 API 写上了，不够再补充。
预览地址: https://stg-ticket.sdjdd.com/docs/1
(因为开发环境的生产环境可能会被用来验收，就又给预备环境绑了个域名)

docs: host api document

---

next/api/src/middleware/auth.ts
next/api/src/query/index.ts
next/api/src/router/index.ts
next/api/src/router/unread.ts

未读小红点功能因为已经有用户在用，所以需要平滑更新。这个 PR 是下面流程中的第一步
- 增加获取未读状态的 REST API
- 用户迁移到新的 API
- API 内部切换成独立 Unread 表
- 上线并迁移用户数据

feat: migrate unread - new API

---

in-app/v1/index.html
in-app/v1/src/App/Categories/index.module.css
in-app/v1/src/App/Categories/index.tsx
in-app/v1/src/App/Home/index.tsx
in-app/v1/src/App/LogIn/index.tsx
in-app/v1/src/App/NotFound/index.tsx
in-app/v1/src/App/Tickets/New/Form/Group/index.module.css
in-app/v1/src/App/Tickets/New/index.tsx
in-app/v1/src/App/Tickets/Ticket/Evaluation/index.tsx
in-app/v1/src/App/Tickets/Ticket/Replies/index.tsx
in-app/v1/src/App/Tickets/Ticket/index.tsx
in-app/v1/src/App/Tickets/index.tsx
in-app/v1/src/App/index.tsx
in-app/v1/src/components/APIError/index.tsx
in-app/v1/src/components/Button/index.tsx
in-app/v1/src/components/FileItem/index.tsx
in-app/v1/src/components/Loading/index.tsx
in-app/v1/src/components/Page/index.module.css
in-app/v1/src/components/Page/index.tsx
in-app/v1/src/components/Time/index.tsx
in-app/v1/src/index.css
in-app/v1/src/utils/useUpload.ts

fix(in-app): adjust styles

---

in-app/v1/src/App/Tickets/Ticket/Replies/index.tsx
in-app/v1/src/App/Tickets/Ticket/index.tsx
in-app/v1/src/App/Tickets/index.tsx

refactor(in-app): replace [].flat with _.flatten

---

modules/Settings/Category.js
modules/config/feature-flags.js
webpack.config.js

fix: get config from remotely

---

in-app/v1/package-lock.json
in-app/v1/package.json
in-app/v1/src/App/Tickets/New/Form/Field/Input/index.tsx
in-app/v1/src/App/Tickets/New/Form/Field/Textarea/index.tsx
in-app/v1/src/App/Tickets/New/Form/Field/Uploader/index.tsx
in-app/v1/src/App/Tickets/New/Form/Field/utils.ts
in-app/v1/src/App/Tickets/Ticket/ReplyInput/index.tsx
in-app/v1/src/App/Tickets/Ticket/index.tsx
in-app/v1/src/App/Tickets/index.tsx
in-app/v1/src/components/Alert/index.tsx
in-app/v1/src/components/FileItem/index.tsx
in-app/v1/src/components/Page/index.module.css
in-app/v1/src/components/Page/index.tsx
in-app/v1/src/components/Preview/index.module.css
in-app/v1/src/components/Preview/index.tsx
in-app/v1/src/components/Uploader/index.tsx
in-app/v1/src/icons/FileVideo.tsx
in-app/v1/src/utils/useUpload.ts
in-app/v1/vite.config.js

feat(in-app): preview image and video

---

api/User.js

fix: newApp flag

---

next/api/src/index.ts
next/api/src/json/reply.ts
next/api/src/json/ticket.ts
next/api/src/model/reply/index.ts
next/api/src/model/ticket/index.ts
next/api/src/router/ticket.ts
next/api/src/utils/xss.ts
next/package-lock.json
next/package.json

边改 DC 的代码边给 v2 API 加一些缺的数据与 API。

feat: 完善 v2 API

---

next/api/src/model2/Group.ts
next/api/src/model2/Role.ts
next/api/src/orm/helpers.ts
next/api/src/orm/model.ts
next/api/src/orm/preloader.ts
next/api/src/orm/query.ts
next/api/src/orm/relation.ts
next/package-lock.json

实现了替换当前使用的旧的 User model 还需要的基于 AV.Relation 的关系。
另外把 package-lock.json 的格式升级成 npm@7 使用的格式了。

feat(next/api): has many through AV.Relation

---

next/api/src/model/OpsLog.ts
next/api/src/model/Reply.ts
next/api/src/model/Ticket.ts
next/api/src/orm/acl.ts
next/api/src/orm/index.ts
next/api/src/orm/model.ts
next/api/src/orm/query.ts
next/api/src/response/ticket.ts
next/api/src/router/ticket-filter.ts
next/api/src/router/ticket.ts

feat(next/api): operate ticket

---

next/api/src/config/index.ts
next/api/src/index.ts
next/api/src/model/File.ts
next/api/src/model/Notification.ts
next/api/src/model/Role.ts
next/api/src/model/Ticket.ts
next/api/src/model/User.ts
next/api/src/model/Vacation.ts
next/api/src/orm/helpers.ts
next/api/src/orm/model.ts
next/api/src/orm/query.ts
next/api/src/router/ticket.ts

写通知的过程中发现了一些用起来不方便的功能，单提个 PR 改善下。

refactor: enhancement

---

modules/NewTicket.js
modules/Ticket/CSReplyEditor/index.js
modules/Ticket/Evaluation.js
modules/Ticket/RecentTickets.js
modules/Ticket/TicketMetadata.js
modules/Ticket/TicketReply.js
modules/Ticket/index.js
next/api/src/router/ticket.ts
package-lock.json
package.json

- 把与触发器相关的创建、更新、回复接口迁到 v2。
- 升级下 open-leancloud-storage。

refactor: switch to next api

---

modules/Ticket/TicketMetadata.js
next/api/src/model/Notification.ts
next/api/src/model/OpsLog.ts
next/api/src/model/Reply.ts
next/api/src/model/Role.ts
next/api/src/model/Ticket.ts
next/api/src/model/User.ts
next/api/src/notification/index.ts
next/api/src/orm/model.ts
next/api/src/router/ticket.ts
next/api/src/ticket/TicketCreator.ts
next/api/src/ticket/TicketUpdater.ts
next/api/src/ticket/index.ts
next/package-lock.json
next/package.json

feat: TicketCreator & TicketUpdater

---

next/api/package-lock.json
next/api/package.json
next/api/src/middleware/error.ts
next/api/src/model/Trigger.ts
next/api/src/response/trigger.ts
next/api/src/router/index.ts
next/api/src/router/trigger.ts
next/api/src/ticket/automation/action/closeTicket.ts
next/api/src/ticket/automation/action/common/index.ts
next/api/src/ticket/automation/action/index.ts
next/api/src/ticket/automation/action/updateAssigneeId.ts
next/api/src/ticket/automation/action/updateCategoryId.ts
next/api/src/ticket/automation/action/updateGroupId.ts
next/api/src/ticket/automation/condition/assigneeId.ts
next/api/src/ticket/automation/condition/authorId.ts
next/api/src/ticket/automation/condition/categoryId.ts
next/api/src/ticket/automation/condition/common/index.ts
next/api/src/ticket/automation/condition/common/mixed.ts
next/api/src/ticket/automation/condition/common/string.ts
next/api/src/ticket/automation/condition/content.ts
next/api/src/ticket/automation/condition/groupId.ts
next/api/src/ticket/automation/condition/index.ts
next/api/src/ticket/automation/condition/status.ts
next/api/src/ticket/automation/condition/title.ts
next/api/src/ticket/automation/index.ts
next/api/src/ticket/automation/trigger/index.ts
next/api/src/utils/zod.ts

在 next 里实现了触发器的基本逻辑和 CRUD 的 api。还没有集成到工单的生命周期中。
就不单独测试了，等前端弄完一块测试吧，节约时间。

feat(next/trigger): trigger mvp

---

next/web/package-lock.json
next/web/package.json
next/web/src/components/antd/index.less
next/web/src/components/antd/index.tsx
next/web/src/styles/antd-override.less
next/web/src/styles/general/variables.less
next/web/src/styles/tds-theme.less
next/web/vite.config.js

1. antd 个别组件不适合按需加载 less 文件,只适合 css 文件 
2. antd 组件之间互相引用比较多，经打包测试引用稍微复杂的组件基本等同全部引用
3. 按需引入带来的便利远不如弊端多

feat: add antd

---

api/stats.js

See: https://jira.xindong.com/browse/TP-36855
自用工单的 Ticket.privateTags 一直未对客户端隐藏，但 schema 文件里设置的是隐藏的（#266）。
随着新功能的加入，重新导入了 Ticket.json，privateTags 就又对客户端隐藏了。
查询相关数据时未使用 masterKey，而是用当前用户的身份。
现改为只允许客服获取统计数据，使用 masterKey 进行查询。

fix(stats): display tag stats

---

next/api/src/model/Category.ts

fix: enlarge count limitation of category query

---

next/web/script/generateEnv.js

Revert "fix: word spelling error"

---

next/api/src/integration/debug.ts
next/api/src/integration/index.ts
next/api/src/integration/mailgun.ts
next/api/src/integration/slack.ts

支持异步加载 integration，因为有的 integration 需要从数据库中读取配置，这个过程不能同步执行。

feat(next/api): install integration asynchronously

---

leanengine.yaml
next/api/nodemon.json
next/api/package-lock.json
next/api/package.json
next/api/src/index.ts

改进 next api 开发体验。使用 typescript 增量编译

改进 next api 开发体验

---

modules/Ticket/ReplyCard.js
modules/Ticket/index.css

Close #408.
给被截断的回复加了个 cover，防止使用者不知道底下还有内容。
[预览效果](https://stg-saas-ticket.leanapp.cn/tickets/38401)

feat: max length of reply card

---

lib/leancloud.js
next/api/package-lock.json
next/api/package.json
next/api/src/config/index.ts
next/api/src/integration/index.ts
next/api/src/integration/jira.ts
plugin/jira.js
resources/schema/JiraIssue.json
server.js

摆脱 TGB-hook-server 的第一步。
因为创建 Jira issue 的功能还是挺常用的，就做成内置的 integration 了，需要时引入即可。

feat: jira integration

---

next/api/src/model/Article.ts
next/api/src/model/Category.ts
next/api/src/orm/helpers.ts
next/api/src/orm/model.ts
next/api/src/response/article.ts
next/api/src/router/article.ts

根据这段时间的使用，觉得 ORM 目前的序列化装饰器用起来不够方便，所以修改一下。

refactor(next): orm

---

next/api/src/router/ticket.ts

fix(next/api): allow reply has only attachments

---

next/api/package-lock.json
next/api/package.json
next/api/src/index.ts
next/api/src/integration/jira.ts
next/api/src/integration/mailgun.ts
next/api/src/integration/slack-plus/SlackNotification.ts
next/api/src/integration/slack-plus/index.ts
next/api/src/integration/slack-plus/message.ts
next/api/src/model/Ticket.ts
next/api/src/model/User.ts
next/api/src/ticket/TicketUpdater.ts
resources/schema/SlackNotification.json

摆脱 tgb-hook-server 的第二步。另一种逻辑的 slack 插件（暂时叫 slack-plus）。目前只有加速器在用。

feat(next/api): slack+ integration

---

api/Ticket.js
api/ticket/api.js
next/api/src/events/index.ts
next/api/src/index.ts
next/api/src/integration/slack.ts
next/api/src/integration/slack/index.ts
next/api/src/integration/slack/message.ts
next/api/src/model/Reply.ts
next/api/src/model/Ticket.ts
next/api/src/notification/index.ts
next/api/src/ticket/TicketCreator.ts
next/api/src/ticket/TicketUpdater.ts
next/api/src/ticket/automation/context.ts
next/api/src/ticket/automation/time-trigger/index.ts
next/api/src/ticket/automation/trigger/index.ts

在用户关闭、已解决工单时发送通知。
在客服添加内部回复时添加通知。

feat(next): notify close ticket & internal reply

---

api/User.js
api/launch.js
server.js

仅在当前应用是新应用时定义 _User afterSave hook。
setTimeout 应该也行，但感觉不太靠谱，还是用一种稳妥的机制来实现吧。

refactor: initialize

---

modules/Ticket/ReplyCard.js
modules/Ticket/index.css

截断（其实是隐藏）长度超过 1000px 的回复内容，点击「展开」后原样显示，不再每条回复单独滚动了。

feat: truncate long reply

---

in-app/v1/src/App/Tickets/Ticket/Replies/index.module.css
in-app/v1/src/App/Tickets/Ticket/Replies/index.tsx
in-app/v1/src/index.tsx
in-app/v1/src/leancloud/index.ts
in-app/v1/src/types/index.ts

简单适配了链接的样式：
Before|After
:-:|:-:

feat(in-app): replies in markdown

---

modules/Ticket/RecentTickets.js
modules/Ticket/index.css

fix: recent ticket title overflow

---

next/api/src/integration/slack/message.ts

feat(integration/slack): split title and content

---

in-app/v1/src/App/Tickets/New/CustomForm/CustomField/CheckboxGroup/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Description.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/ErrorMessage.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Input/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/RadioGroup/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Select/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Textarea/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Uploader/index.tsx
in-app/v1/src/api/category.ts

给内嵌页面加上自定义字段描述。描述和错误信息共用一个位置，优先展示错误信息。
临时 suo 了个组件来展示描述和错误信息，感觉放到 `<Group />` 里比较好。下次重构的时候再说吧。

feat(in-app): custom field description

---

in-app/v1/package-lock.json
in-app/v1/package.json
in-app/v1/src/App/Articles/index.tsx
in-app/v1/src/App/Categories/index.tsx
in-app/v1/src/App/LogIn/index.tsx
in-app/v1/src/App/Tickets/Ticket/index.tsx
in-app/v1/src/App/Tickets/index.tsx
in-app/v1/src/App/index.tsx
in-app/v1/src/api/category.ts
in-app/v1/src/components/ControlButton/index.tsx

试试 react-router-dom@6 的水。
看了升级指南和 API 文档，和 5.x 的差别还是挺大的。因为 in-app 用到的特性不多，所以升起来简单。升控制台的时候应该会很痛苦 :dh-doge:

feat(in-app): use react-router-dom@6

---

modules/Ticket/CSReplyEditor/MarkdownEditor.js
modules/Ticket/index.css

fix: check null value in callback ref

---

next/web/package-lock.json
next/web/package.json
next/web/src/App/Admin/Setting/Automations/TimeTriggers/Detail.tsx
next/web/src/App/Admin/Setting/Automations/TimeTriggers/New.tsx
next/web/src/App/Admin/Setting/Automations/TimeTriggers/index.tsx
next/web/src/App/Admin/Setting/Automations/Triggers/Detail.tsx
next/web/src/App/Admin/Setting/Automations/Triggers/New.tsx
next/web/src/App/Admin/Setting/Automations/Triggers/index.tsx
next/web/src/App/Admin/Setting/Automations/index.tsx
next/web/src/App/Admin/Setting/index.tsx
next/web/src/App/Admin/Sidebar/index.tsx
next/web/src/App/Admin/Tickets/index.tsx
next/web/src/App/Admin/index.tsx
next/web/src/App/Login/index.tsx
next/web/src/App/index.tsx
next/web/src/components/Sentry/ErrorBoundary.tsx
next/web/src/components/Sentry/index.tsx
next/web/src/utils/useSearchParams.tsx

feat(next/web): upgrade react-router-dom to 6.0.2

---

next/api/src/model/Organization.ts
next/api/src/response/organization.ts
next/api/src/router/index.ts
next/api/src/router/organization.ts

feat(next/api): get organizations

---

modules/NewTicket.js
modules/category/index.js

fix: get more categories

---

next/web/package-lock.json
next/web/package.json
next/web/script/generateEnv.js
next/web/src/App/Tickets/New/TicketForm/CustomFields.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/CheckboxGroup.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Input.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/RadioGroup.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Select.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Textarea.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Upload.tsx
next/web/src/App/Tickets/New/TicketForm/LeanCloudAppSelect.tsx
next/web/src/App/Tickets/New/TicketForm/OrganizationSelect.tsx
next/web/src/App/Tickets/New/TicketForm/index.module.css
next/web/src/App/Tickets/New/TicketForm/index.tsx
next/web/src/App/Tickets/New/index.tsx
next/web/src/App/Tickets/index.tsx
next/web/src/App/index.tsx
next/web/src/api/category.ts
next/web/src/api/organization.ts
next/web/src/global.d.ts
next/web/src/leancloud/index.ts

在 next-web 里重新实现了 ticket 表单，便于在此之上继续实现新功能。
已部署到测试环境（https://REPLACE/next/tickets/new）。

feat(next/web): TicketForm

---

modules/Ticket/RecentTickets.js
modules/Ticket/index.css
modules/User.js
modules/i18n/locales/en.json
modules/i18n/locales/zh.json

context: https://xindong.slack.com/archives/C01EN4GRJQP/p1638766193130000?thread_ts=1638764990.124800&cid=C01EN4GRJQP
以及顺手增加了一些行距。

feat: add all tickets link to recent tickets section

---

next/web/package-lock.json
next/web/package.json
next/web/postcss.config.js
next/web/src/App/Admin/Settings/Automations/TimeTriggers/index.tsx
next/web/src/App/Admin/Settings/Automations/Triggers/index.tsx
next/web/src/App/Admin/Settings/Automations/components/TriggerForm/Conditions.tsx
next/web/src/App/Admin/Settings/Menu.tsx
next/web/src/App/Admin/Settings/index.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Filter/FilterMenu/FilterSearch.tsx
next/web/src/App/Admin/Tickets/Filter/FilterMenu/index.tsx
next/web/src/App/Admin/Tickets/TicketView/TicketList/index.tsx
next/web/src/App/Admin/Tickets/TicketView/TicketTable/index.tsx
next/web/src/App/Admin/Tickets/Topbar/BatchUpdateDialog/index.tsx
next/web/src/App/Admin/Tickets/Topbar/index.tsx
next/web/src/App/Admin/Tickets/index.tsx
next/web/src/App/Admin/Topbar/index.tsx
next/web/src/App/Admin/index.tsx
next/web/src/components/Menu.tsx
next/web/tailwind.config.js

feat(next/web): tailwindcss 3

---

modules/Settings/index.js

feat: apply new setting pages

---

modules/Ticket/CSReplyEditor/MarkdownEditor.js
modules/Ticket/CSReplyEditor/index.js
modules/Ticket/CSReplyEditor/index.module.scss
modules/Ticket/EditReplyModal.js
modules/Ticket/ReplyCard.js
modules/Ticket/index.js
next/api/src/router/index.ts
next/api/src/router/reply.ts

支持修改回复。
jj 定的 p2 任务是：
> 消息撤回：客服可能在回复内容上失误，需要进行措辞更改
删除回复之前是 yw 做的，这回加上修改功能应该就符合需求了。

feat: modify reply

---

next/api/src/orm/query.ts

直接使用 SDK 提供的 AV.Query#findAndCount，少发一次请求，提高一点点效率。

refactor(next/api): Query#findAndCount

---

next/api/src/integration/jira.ts

需求：https://xindong.slack.com/archives/C01UB1M7BBK/p1640836652147000
增加配置 categoryAssignees，用来指定某一分类对应的 Jira Issue 负责人。

feat(next/jira): set assignee by ticket category

---

in-app/v1/package-lock.json
in-app/v1/package.json
in-app/v1/src/App/Tickets/New/usePersistFormData.ts
in-app/v1/src/App/index.tsx
in-app/v1/vite.config.js

Fix: [TP-55746](https://jira.xindong.com/browse/TP-55746), [TP-55516](https://jira.xindong.com/browse/TP-55516)

fix(in-app): QA issues

---

next/web/package-lock.json
next/web/package.json
next/web/src/App/Admin/Tickets/Filter/FilterForm/AssigneeSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/CreatedAtSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/GroupSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Filter/useTicketFilter.ts
next/web/src/api/ticket.ts
next/web/src/utils/date-range.ts

新增：工单列表页可根据 createdAt 的范围筛选工单。
另外把 vite 的版本限定在 2.6.x，2.7 往后 hmr 有点问题，等官方修复后再升上去。还删除了一些没用到的功能。

feat(next/web): filter tickets by date range of createdAt

---

next/api/src/common/http/handler/param/index.ts
next/api/src/common/http/handler/param/pagination.ts
next/api/src/common/http/index.ts

feat(next/api): common

---

next/web/src/App/Admin/Settings/Articles/EditArticleForm.tsx
next/web/src/App/Admin/Settings/Articles/index.tsx
next/web/src/App/Admin/Settings/Automations/TimeTriggers/Detail.tsx
next/web/src/App/Admin/Settings/Automations/TimeTriggers/New.tsx
next/web/src/App/Admin/Tickets/TicketView/TicketList/index.tsx
next/web/src/App/Admin/Tickets/Topbar/batchUpdate.ts
next/web/src/App/Admin/Topbar/index.tsx
next/web/tsconfig.json
next/web/vite.config.js

refactor(next/web): import path alias

---

next/api/src/orm/query.ts
next/api/src/router/notification.ts
next/api/src/router/ticket.ts

fix(next/api): query condition

---

api/stats.js

丰老师反应 dc 的月度统计不能看，报 429 的错误。看代码是没有做并发的限制，玩了命的查。
先临时限制下并发数吧，反正新的统计已经在做了 🏃 。
其实前端页面也会发一堆请求，只是目前还没有触发限制 :可怕:

feat: limit stats concurrency

---

next/web/src/App/Admin/Views/index.tsx

See: https://xindong.slack.com/archives/C01RY5JHB47/p1642591862030200

fix(next/web): replace navigate to view page

---

next/web/src/App/Admin/Views/index.tsx

fix(next/web): always display shared views

---

next/web/package-lock.json
next/web/package.json
next/web/src/App/Tickets/New/TicketForm/Fields/CheckboxGroup.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Help/index.module.css
next/web/src/App/Tickets/New/TicketForm/Fields/Help/index.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Input.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/RadioGroup.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Select.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Textarea.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Upload.tsx
next/web/src/App/Tickets/New/TicketForm/index.module.css
next/web/src/App/Tickets/New/TicketForm/index.tsx

自定义字段描述支持 markdown。（主要用于展示备案授权书的链接 👀 ）

feat(next/web): custom field help support markdown content

---

next/api/src/controller/ticket-field.ts
next/api/src/model/TicketField.ts
next/api/src/response/ticket-field.ts
next/web/src/App/Admin/Settings/TicketForms/EditTicketForm.tsx
next/web/src/api/ticket-field.ts

feat(next/web): ticket form preview

---

next/api/src/response/category.ts
next/api/src/router/article.ts
next/web/src/App/Tickets/New/TicketForm/index.tsx
next/web/src/api/article.ts
next/web/src/api/category.ts
next/web/src/components/common/CategorySelect.tsx
next/web/src/components/common/Retry.tsx

显示分类路径中所有分类的 FAQ。
useQueries 用着好别扭啊，是我用的不对吗 🤔

feat(next/web): display faqs for category path

---

next/web/src/App/Tickets/New/TicketForm/index.tsx

https://xindong.slack.com/archives/C01RY5JHB47/p1643269981089400

feat(next/web): open link in new tab

---

next/web/src/App/Admin/Settings/Categories/index.tsx

feat(next/web): category setting promotion

---

next/api/src/router/ticket.ts
next/web/src/App/Admin/Search/index.tsx
next/web/src/App/Admin/Sidebar/index.tsx
next/web/src/App/Admin/index.tsx
next/web/src/api/ticket.ts

https://xindong.slack.com/archives/C01RY5JHB47/p1644312077271809?thread_ts=1642508550.016300&cid=C01RY5JHB47
先实现，再优化，不行加机器。

feat(next): search tickets by custom field

---

next/web/src/App/Admin/Settings/Articles/EditArticleForm.tsx
next/web/src/components/MarkdownEditor/index.tsx

https://github.com/nhn/tui.editor/issues/2238

feat: persist user preference in EditorMode

---

next/api/src/router/ticket.ts
next/web/src/App/Admin/Search/index.tsx
next/web/src/api/ticket.ts

搜索功能的一些优化：
- 支持完整的 q 查询语法
- 用新标签页打开工单
- 其他 UX 优化

feat(next): tickets searching promotion

---

Deploy.md
docs/api2.yml
in-app/v1/src/App/Articles/index.tsx
next/api/src/model/Article.ts
next/api/src/model/ArticleFeedback.ts
next/api/src/router/article.ts
resources/schema/FAQFeedback.json
resources/schema/FAQRevision.json

feat(Articles): submit feedback

---

next/api/src/controller/category.ts
next/api/src/model/Category.ts
next/api/src/response/category.ts
next/api/src/service/category.ts
next/web/src/App/Admin/Settings/Automations/components/CategorySelect.tsx
next/web/src/App/Admin/Settings/Categories/index.tsx
next/web/src/api/category.ts
next/web/src/components/common/CategorySelect.tsx

终极完善分类列表管理：
- 支持调整顺序
- 多项 UX 改进

feat(next): categories management

---

modules/Settings/index.js
next/api/src/controller/tag-metadata.ts
next/api/src/model/TagMetadata.ts
next/api/src/response/tag-metadata.ts
next/web/src/App/Admin/Settings/Menu.tsx
next/web/src/App/Admin/Settings/Tags/TagMetadataForm.tsx
next/web/src/App/Admin/Settings/Tags/index.module.css
next/web/src/App/Admin/Settings/Tags/index.tsx
next/web/src/App/Admin/Settings/index.tsx
next/web/src/api/tag-metadata.ts

feat(next): tag metadata setting

---

next/api/src/controller/group.ts

fix(next-api): group description is optional

---

modules/Ticket/ReplyCard.js
next/api/package-lock.json
next/api/package.json
next/api/src/response/article-revision.ts
next/api/src/response/article.ts
next/api/src/response/reply.ts
next/api/src/response/ticket.ts
next/api/src/utils/xss.ts
package-lock.json
package.json

feat: replace xss with DOMPurify

---

server.js

Will use the http redirect feature provided by LeanEngine instead.

feat: remove http redirect

---

api/ticket/api.js
api/ticket/model.js
modules/GlobalNav.js
modules/Ticket/AccessControl/index.js
modules/Ticket/AccessControl/index.module.scss
modules/Ticket/index.js
next/api/src/router/article.ts
next/api/src/router/ticket.ts

feat(Ticket): access control

---

api/common.js
index.js
modules/Avatar.js
modules/GlobalNav.js
modules/StatsChart.js
modules/StatsSummary.js
modules/Ticket/CSReplyEditor/index.js
modules/Ticket/ReplyCard.js
modules/Ticket/index.js
modules/common.js
modules/i18n/locales/en.json
modules/i18n/locales/ko.json
modules/i18n/locales/zh.json
next/api/package-lock.json
next/api/package.json
next/api/src/model/Article.ts
next/api/src/model/User.ts
next/api/src/router/ticket.ts
next/api/src/ticket/automation/trigger/index.ts
package-lock.json
package.json

第一个 commit 是在原来的设定上把 bug 修了，确保所有的地方都「先处理特殊的（customerService）再处理其他的」，这样切换到新的实现也不会有问题。
第二个 commit 是重构。

refactor: reimplement isStaff/isCustomerService with Role query

---

Deploy.md
README.md
deploy/index.mjs
deploy/utils.mjs
package-lock.json
package.json
resources/schema/OpsLog.json

之前做的自动部署脚本。还不完善但是先发出来，虽然之后会往多租户方向开发但是这个对独立部署也还是有用的。

feat: automate deploy script

---

next/api/src/ticket/TicketUpdater.ts
next/api/src/ticket/automation/action/addTag.ts
next/api/src/ticket/automation/context.ts
next/api/src/ticket/automation/time-trigger/action/index.ts
next/api/src/ticket/automation/trigger/action/index.ts
next/web/package-lock.json
next/web/package.json
next/web/src/App/Admin/Settings/Automations/TimeTriggers/actions/index.ts
next/web/src/App/Admin/Settings/Automations/Triggers/actions/index.ts
next/web/src/App/Admin/Settings/Automations/actions/AddTag.tsx
next/web/src/App/Admin/Settings/Automations/components/TriggerForm/CustomField.tsx

https://xindong.slack.com/archives/C01RY5JHB47/p1646810532737339
实现该需求的第一步：增加「添加 Tag」的触发器操作。
顺便升了一下 react-hook-form 的版本。

feat(next): add tag trigger action

---

in-app/v1/src/App/Categories/index.tsx
in-app/v1/src/App/Home/index.tsx
in-app/v1/src/App/NotFound/index.tsx
in-app/v1/src/App/Tickets/index.tsx
in-app/v1/src/App/index.tsx
in-app/v1/src/i18n/locales/zh.json
in-app/v1/src/types/index.ts
next/api/src/common/http/index.ts
next/api/src/controller/category.ts
next/api/src/model/Category.ts
next/api/src/orm/model.ts
next/api/src/response/category.ts
next/api/src/service/category.ts
next/web/src/App/Admin/Settings/Categories/CategoryForm.tsx
next/web/src/App/Admin/Settings/Categories/index.tsx
next/web/src/api/category.ts
package.json
resources/schema/Category.json

https://xindong.slack.com/archives/C01RY5JHB47/p1647484027290599?thread_ts=1647483569.316309&cid=C01RY5JHB47

feat: category alias and sub categories API

---

next/api/src/cloud/ticketStats.ts
next/web/src/App/Admin/Stats/Chart/Interactions.ts
next/web/src/App/Admin/Stats/Chart/index.tsx
next/web/src/App/Admin/Stats/StatsDetails.tsx
next/web/src/App/Admin/Stats/StatusPage.tsx
next/web/src/App/Admin/Stats/utils.tsx
next/web/src/api/ticket-stats.ts
next/web/src/components/Page/SubMenu/SiderMenu.tsx

[测试地址](https://stg-ticket.sdjdd.com/next/admin/stats?from=2022-02-01&to=2022-02-28)
只有 2月份有数据

fix(stats): aggregated data use chart zoom

---

next/api/src/index.ts
next/api/src/middleware/auth.ts

- 无效的凭证返回 401 而不是 403（forbidden）
- 根据基本法返回的 error 加上了字符串类型的 code

fix(api): string typed error code

---

api/next-shim.js
docs/api2.yml
in-app/v1/src/App/Home/index.tsx
in-app/v1/src/App/Tickets/index.tsx
next/api/src/controller/category.ts
next/api/src/model/Notification.ts
next/api/src/model/Ticket.ts
next/api/src/notification/index.ts
next/api/src/notification/migrate.ts
next/api/src/router/notification.ts
next/api/src/router/ticket.ts
next/api/src/router/unread.ts
next/api/src/service/category.ts
next/api/src/ticket/TicketUpdater.ts
resources/schema/notification.json

API 变化：
- 以下 API 加了 product 参数
- GET /tickets 
- GET /unread 
- GET /notifications
- POST /notifications/read-all
已部署到 https://demo.leanticket.cn

feat: in-app 支持 product 概念

---

next/api/src/controller/group.ts

feat(next/api): add and remove group members separately

---

next/api/src/common/http/error.ts
next/api/src/controller/category.ts
next/api/src/controller/ticket-field.ts
next/api/src/model/Category.ts
next/api/src/model/TicketField.ts
next/api/src/model/User.ts
next/api/src/response/category.ts
next/api/src/response/ticket-field.ts
next/web/src/App/Admin/Settings/Categories/CategoryForm.tsx
next/web/src/App/Admin/Settings/Categories/index.tsx
next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx
next/web/src/App/Admin/Settings/TicketFields/index.tsx
next/web/src/App/Admin/components/JSONTextarea.tsx
next/web/src/api/category.ts
next/web/src/api/ticket-field.ts
resources/schema/Category.json
resources/schema/TicketField.json

TicketField 的 meta 属性是留给开发者自己配置的，用于支持一些自定义的需求。
Category 的类似，我待会发上来。

feat: meta of TicketField and Category

---

in-app/v1/src/App/Tickets/New/index.tsx
next/api/src/controller/category.ts
next/api/src/model/TicketForm.ts
next/api/src/response/category.ts
next/api/src/response/ticket-field.ts
next/api/src/router/ticket-form.ts
next/api/src/router/ticket.ts
next/web/src/App/Admin/Settings/TicketForms/EditTicketForm.tsx
next/web/src/App/Admin/Settings/TicketForms/index.tsx
resources/data/TicketField.jsonl
resources/data/TicketFieldVariant.jsonl
resources/data/TicketForm.jsonl

As per https://xindong.slack.com/archives/C01RY5JHB47/p1651676188132689

feat: make system fields optional

---

api/file/api.js
api/file/utils.js
docs/api2.yml
modules/Ticket/ReplyCard.js
modules/components/CustomField/index.js
modules/components/CustomField/index.module.scss
next/api/src/controller/category.ts
next/api/src/controller/file.ts
next/api/src/model/ArticleTopic.ts
next/api/src/model/File.ts
next/api/src/response/file.ts
next/api/src/utils/index.ts

支持外部 private bucket 通过 download token 访问文件。
以为很简单的改动，改完 v2 发现 v1 API 也要改，改完发现前端也要改。

feat: support external private qiniu files

---

next/web/package-lock.json
next/web/package.json
next/web/script/generateEnv.js
next/web/src/App/Admin/Stats/ReplyDetails.tsx
next/web/src/App/Tickets/New/TicketForm/docsearch-override.css
next/web/src/App/Tickets/New/TicketForm/docsearch.d.ts
next/web/src/App/Tickets/New/TicketForm/index.tsx
next/web/src/global.d.ts
next/web/vite.config.js

See: https://xindong.slack.com/archives/C01EN4GRJQP/p1653965828536439?thread_ts=1653927649.804359&cid=C01EN4GRJQP

feat(next/web): docsearch

---

in-app/v1/src/App/Articles/index.tsx
in-app/v1/src/App/Articles/utils.tsx
in-app/v1/src/types/index.ts
next/api/package-lock.json
next/api/package.json
next/api/src/declear.d.ts
next/api/src/response/article.ts
next/web/src/App/Admin/Settings/Articles/index.tsx
next/web/src/api/article.ts

原始需求是想要在文章后台能复制最终用户可见的 URL。
在此基础上在 URL 里增加了标题（会被忽略）。

feat: slugify article URLs

---

next/api/src/model/User.ts

https://xindong.slack.com/archives/C01UB1M7BBK/p1655977976846199
https://xindong.slack.com/archives/C01TLAHFTBJ/p1655992722682529

fix(jwt): correct the race condition error matching

---

package-lock.json
package.json
server.js

feat: prevent creating too much connections

---

modules/Ticket/ReplyCard.js
next/api/src/utils/xss.ts

https://xindong.slack.com/archives/C01UB1M7BBK/p1656993894590449

fix(md): forbid style tags/attrs

---

next/web/src/App/Admin/Settings/Automations/Triggers/actions/UpdateAssigneeId.tsx
next/web/src/App/Admin/Settings/Automations/Triggers/conditions/AssigneeId.tsx
next/web/src/App/Admin/Settings/Automations/actions/UpdateAssigneeId.tsx
next/web/src/App/Admin/Settings/Automations/actions/UpdateGroupId.tsx
next/web/src/App/Admin/Settings/Automations/conditions/AssigneeId.tsx
next/web/src/App/Admin/Settings/Automations/conditions/GroupId.tsx
next/web/src/App/Admin/Settings/Views/EditView.tsx
next/web/src/App/Admin/Settings/Views/conditions.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/AssigneeSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/GroupSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Topbar/index.tsx
next/web/src/App/Admin/Tickets/index.tsx
next/web/src/components/antd/index.tsx
next/web/src/components/common/CustomerServiceSelect.tsx
next/web/src/components/common/GroupSelect.tsx

主要为视图的 assignee 与 group 条件增加了 null 选项（代表未指定）。为了更多选分开，特地拆出了 SingleXXXSelect。
另外列表页过滤工具换了个图标，并把默认视图改为了 table。

fix(view): allow nulls as condition values

---

Deploy.md
next/web/src/App/Tickets/New/TicketForm/index.tsx

Context: https://xindong.slack.com/archives/C01RY5JHB47/p1660621888535439?thread_ts=1660615676.519629&cid=C01RY5JHB47
自用提单页需要忽略系统字段的配置，所以把漏加的系统字段补上。另外更新一下部署文档。

feat: ignore system fields

---

next/api/src/model/TicketLog.ts
next/api/src/router/ticket-stats.ts
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Topbar/index.tsx
next/web/src/App/Admin/Tickets/index.tsx

fix: analysis error

---

modules/Login.js

https://xindong.slack.com/archives/C01U6KHER7G/p1662117049617389?thread_ts=1658483058.892339&cid=C01U6KHER7G

feat: retire password login

---

modules/Ticket/TicketMetadata.js
next/api/src/model/OpsLog.ts
next/api/src/router/ticket.ts

在 v2 里实现设置自定义字段值管理的功能。
API 设计方面就不搞啥创新了，完全照搬 v1，只是重新实现一下，给 DC 使用。
自用前端也切到新 API 上。

feat(next/api): custom field values management

---

next/api/src/router/ticket.ts

为 DC 工单详情页实现预览自定义字段提交的文件，一开始打算用 SDK 查，弄完发现 _File class 不允许 find。
倒是有个 `GET /api/1/files?id=1,2,3` 的 API，不过不太想用。对前端比较友好的方式就是自动为文件类型的字段值填充文件信息。
所以现在 `GET /api/2/tickets/:id/custom-fields` 会带上文件信息：
```json
[
{
"field": "61e8ea9c932a0d2ee4159dc1",
"value": "foo"
},
{
"field": "61e8eab8932a0d2ee4159dfa",
"value": ["bar","baz"]
},
{
"field": "61e8eb1b660f434c1b1b58a7",
"value": [
"61ef764fb31a5c755f62f872"
],
"files": [
{
"id": "61ef764fb31a5c755f62f872",
"name": "filename.png",
"mime": "image/png",
"url": "https://example.com/filename.png"
}
]
}
]
```

feat: attach .files to file field value

---

Deploy.md
next/api/src/cloud/utils.ts
next/api/src/router/ticket.ts
next/api/src/utils/textFilter.ts

增加文本过滤，只过滤用户输入而不过滤客服输入，对回复、工单标题内容、工单字段（仅文本和多行文本）进行过滤
[预览环境](https://28f6d945-a21d-444c-af4d-00b9ea11d8f2.cn-e1.leanapp.cn)

feat(next/api): text filter

---

Deploy.md
next/api/src/cloud/utils.ts
next/api/src/utils/textFilter.ts

perf(next/api): improve retry when request failed in text filter

---

next/api/src/router/ticket.ts
next/api/src/utils/textFilter.ts

如果文本过滤服务挂了就降级一分钟，直接返回原文本，以及不过滤选项字段了

perf: text filter downgrade

---

modules/UserLabel.js
package-lock.json
package.json

给 UserLabel 加了个 popover 菜单，不过好像箭头那里有点偏移？
[预览环境](https://1cf79e44-e5e1-4efa-b449-17da254f8054.cn-e1.leanapp.cn)

feat: popover menu on user label

---

next/api/src/router/ticket.ts

Context: https://xindong.slack.com/archives/C01RY5JHB47/p1664182206830939

feat(next/api): strip empty custom field value

---

next/api/src/response/file.ts

https://xindong.slack.com/archives/C01UB1M7BBK/p1664251401625669

feat(file): external video thumbnail

---

next/api/src/controller/ticket-field.ts
next/api/src/response/ticket-field.ts

减少在查询字段统计时向clickhouse调api的次数
[预览环境](https://stg-28f6d945-a21d-444c-af4d-00b9ea11d8f2.cn-e1.leanapp.cn )

perf(next/api): reduce request times when fetch field stats

---

next/api/src/router/ticket.ts
next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx

如果 TicketField 的 meta 里有个叫 disableFilter 的字段且值为 true 就不过滤

perf(next/api): configurable filter settings via meta in TicketField

---

docs/api2.yml
next/api/src/response/ticket-stats.ts
next/api/src/router/ticket-stats.ts
next/web/src/App/Admin/Stats/StatsDetails.tsx
next/web/src/api/ticket-stats.ts

fix: evaluation duplicate stats

---

Deploy.md
next/api/src/router/ticket.ts
next/api/src/utils/textFilter.ts

修复了当不传 title 时会用被 escape 掉的 content 的 bug，现在是用未 escape 的 content

fix(next/api): fix filtered text is mistakenly escaped in title

---

next/web/src/App/Admin/Stats/StatsPage.tsx

cc https://xindong.slack.com/archives/C01RY5JHB47/p1663927598797779
原因: react 异步更新，antd 组件的 2 个事件获取同一个值
另外不再展示禁用的分类

fix: category selector value change error

---

modules/Ticket/Evaluation.js
modules/i18n/locales/zh.json
next/api/src/router/ticket.ts

工单页面显示用户的评价选项，评价内容接入文本过滤（不包含选项）

feat: selections display

---

Deploy.md
in-app/v1/src/App/Articles/index.tsx
in-app/v1/src/App/index.tsx
in-app/v1/src/components/APIError/index.tsx
next/api/src/controller/user.ts
next/api/src/model/User.ts
resources/schema/_User.json

remove unused auth and tags params.
这个 RP 只负责写入，展示部分另提 PR。

feat(in-app): xd-access-token login support

---

next/api/src/controller/user.ts
next/api/src/model/User.ts

主干上只提供读接口。具体的展示逻辑作为配置在具体分支维护： https://github.com/leancloud/ticket/commit/97df22a08146abacaddc88fb32393f7e215c6c44

feat(api): GET /users/:id/third-party-data

---

in-app/v1/src/App/index.tsx
in-app/v1/src/index.css

> 在 in-app 页面明显的地方区分标出这是测试环境
https://xindong.atlassian.net/wiki/spaces/TDS/pages/455123389/XDSDK#%E8%A1%A5%E5%85%85%E8%AF%B4%E6%98%8E

feat(in-app): RND mode

---

modules/Ticket/Category/index.js
modules/Ticket/TicketMetadata.js
next/api/src/controller/category.ts

fix: render DC for /products/:id/categories

---

in-app/v1/src/App/Tickets/New/index.tsx

in-app 支持通过 `#fields={"key":"value"}` 设置自定义字段值。
如果字段在表单中显示，会将该值作为初始值，否则默默地提交。未知字段的值将存到 metaData 中。

feat(in-app): preset field values

---

in-app/v1/src/components/NoData/index.tsx
in-app/v1/src/components/QueryWrapper/index.tsx
in-app/v1/src/states/auth.ts

一些定义上的优化，是实现 [XD 跳转逻辑](https://github.com/leeyeh/ticket/commit/b33e6c390039d8ba049ae0c596d0d98a15a8985e) 时的一些通用改动。

refactor: types

---

modules/Ticket/TicketMetadata.js
modules/components/CustomField/index.js

- add user to the ctx
- support #DEFAULT# placeholder

feat: enhance field preview template

---

in-app/v1/src/index.tsx
in-app/v1/src/local-storage.polyfill.ts

https://xindong.slack.com/archives/C01RY5JHB47/p1668593069272589

feat(in-app): local storage polyfill

---

in-app/v1/src/App/Tickets/New/usePersistFormData.ts
in-app/v1/src/env/index.ts
in-app/v1/src/env/local-storage.ts
in-app/v1/src/index.tsx
in-app/v1/src/leancloud/index.ts

https://xindong.slack.com/archives/C01RY5JHB47/p1668656693931139?thread_ts=1668593069.272589&cid=C01RY5JHB47

feat(in-app): pure localStorage polyfill

---

api/next-shim.js
next/api/src/model/User.ts
next/api/src/utils/jwt.ts

refactor(user): refactor tds user login

---

next/api/src/cache/redis.ts
next/api/src/controller/user.ts
next/api/src/middleware/auth.ts
next/api/src/model/User.ts
next/api/src/utils/jwt.ts

ctx: https://xindong.atlassian.net/wiki/spaces/TDS/pages/475599233/TDS

feat(User): impl tds user login logic

---

docs/api2.yml

docs: update docs

---

Deploy.md
next/api/src/controller/user.ts
next/api/src/utils/jwt.ts

fix: use another environment variable to store tds user signing key

---

in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Date/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/NumberInput/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/index.tsx
in-app/v1/src/i18n/locales/zh.json
in-app/v1/src/index.css
modules/components/CustomField/index.js
next/api/src/model/TicketField.ts
next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx
next/web/src/App/Admin/Settings/TicketFields/TicketFieldIcon.tsx
next/web/src/App/Admin/Settings/TicketFields/TicketFieldType.tsx
next/web/src/App/Tickets/New/TicketForm/CustomFields.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Date.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Number.tsx
next/web/src/api/ticket-field.ts

feat: more form field type

---

api/ticket/api.js
docs/api1.yml
next/api/src/model/Ticket.ts
next/api/src/router/ticket.ts
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Filter/useTicketFilter.tsx
next/web/src/App/Admin/Tickets/TicketView/TicketTable/index.tsx
next/web/src/App/Admin/Tickets/Topbar/index.tsx
next/web/src/App/Admin/components/TicketLink.tsx
next/web/src/App/Admin/components/TicketStatus.tsx
next/web/src/api/ticket.ts

feat: participants

---

modules/Home.js

重定向 `/` 到 `/next/admin/tickets`

perf: redirect old main page to next

---

next/api/src/ticket/automation/condition/content.ts
next/api/src/ticket/automation/trigger/condition/index.ts
next/api/src/ticket/automation/trigger/condition/replyContent.ts
next/api/src/ticket/automation/trigger/context.ts
next/api/src/ticket/automation/trigger/index.ts
next/web/src/App/Admin/Settings/Automations/Triggers/conditions/index.ts

feat: reply content trigger condition

---

Deploy.md
api/next-shim.js
next/api/src/cloud/index.ts
next/api/src/cloud/ticketStats/slack.ts
next/api/src/cloud/ticketStats/utils.ts
next/api/src/integration/slack-plus/index.ts
next/api/src/integration/slack/index.ts
next/api/src/model/TicketStats.ts
next/api/src/utils/textFilter.ts
next/api/src/utils/types.ts
resources/schema/TicketStats.json

feat: slack report

---

next/api/src/controller/view.ts
next/web/package-lock.json
next/web/package.json
next/web/src/App/Admin/Settings/Views/EditView.tsx
next/web/src/App/Admin/Settings/Views/index.tsx
next/web/src/api/view.ts

fix: update view visiblity

---

Deploy.md
resources/schema/_User.json

fix(schema): disable create permission for _User table

---

in-app/v1/src/App/index.tsx
next/api/src/middleware/auth.ts

填上独立部署缺的最后两块拼图： https://xindong.atlassian.net/wiki/spaces/TDS/pages/479172567

feat: JWT support for auth and in-app

---

next/api/src/controller/user.ts
next/api/src/model/User.ts

密码登录时把 code == 210 的 error 转换成 InvalidLoginCredentialError

fix: user login sentry and error

---

next/web/package-lock.json
next/web/package.json
next/web/src/App/Admin/Settings/Automations/Triggers/actions/UpdateAssigneeId.tsx
next/web/src/App/Admin/Settings/Automations/Triggers/conditions/AssigneeId.tsx
next/web/src/App/Admin/Settings/Automations/Triggers/conditions/AuthorId.tsx
next/web/src/App/Admin/Settings/Automations/Triggers/conditions/CurrentUserId.tsx
next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx
next/web/src/api/ticket-field.ts
next/web/src/api/ticket-form.ts
next/web/src/components/Chart/index.tsx

修复 next/web 中的各种因为疏忽、库升级、项目 ts 版本和 vscode 版本不匹配导致的类型错误。

fix(next/web): ts error

---

Deploy.md
api/next-shim.js
modules/Ticket/TicketMetadata.js
next/api/src/common/http/error.ts
next/api/src/controller/customer-service.ts
next/api/src/model/User.ts
next/api/src/response/user.ts
next/api/src/router/ticket.ts
next/api/src/ticket/TicketCreator.ts
next/web/src/App/Admin/Settings/Members/index.tsx
next/web/src/api/customer-service.ts
next/web/src/api/user.ts
next/web/src/components/common/CustomerServiceSelect.tsx
resources/schema/_User.json

ctx: https://xindong.slack.com/archives/C01UB1M7BBK/p1667552842889979
给用户增加 active 属性，inactive 用户不能登录，在自动选择负责人时候不会被选中，不能被分配工单，但是还可以被放入用户组

feat: inactive agent

---

next/api/src/router/ticket.ts
next/api/src/ticket/export/ExportTicket.ts
next/api/src/ticket/export/index.ts

本来要改 csv 导出格式，但发现现在的导出功能是有问题的。就先修一些小问题，有时间重写罢。

fix(next/api): [ticket export] typo

---

next/api/src/cloud/ticketStats/slack.ts

将 slack 周报的周期改为 周五的00:00:00到周四的23:59:59

refactor(next/api): change weekly slack report period

---

next/api/src/controller/user.ts

fix(next/api): fix permission when pre create user

---

next/api/package-lock.json
next/api/package.json
next/api/src/model/User.ts
next/api/src/orm/model.ts

chore(next/api): upgrade typescript to v4.9.4

---

modules/Ticket/CSReplyEditor/QuickReplySelector.js
modules/Ticket/CSReplyEditor/index.module.scss
next/api/src/controller/article-topic.ts
next/api/src/controller/quick-reply.ts
next/web/src/App/Admin/Settings/QuickReplies/index.tsx
next/web/src/App/Admin/Settings/TicketFields/index.tsx
next/web/src/api/quick-reply.ts
next/web/src/api/ticket-field.ts

- 分页显示快捷回复
- 根据名称和内容过滤快捷回复
- 切换到 API 2

feat: filter quick reply

---

Deploy.md
next/api/src/cloud/ticketStats/slack.ts
next/api/src/integration/slack-plus/index.ts
next/api/src/response/ticket-stats.ts

周报周期可以通过配置进行调整，发送到的 slack channel 也可以调整
同时修复了好评率一直为 `--` 的 bug

feat: configurable start day of stats period

---

next/api/src/orm/query.ts
next/api/src/router/ticket.ts
next/api/src/ticket/export/ExportTicket.ts
next/web/src/App/Admin/Settings/Categories/CategoryFieldStats.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/AssigneeSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/CategorySelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/CreatedAtSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/EvaluationStarSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/FieldSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/GroupSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/StatusSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/TagSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Filter/useSorterLimited.tsx
next/web/src/App/Admin/Tickets/Filter/useTicketFilter.tsx
next/web/src/App/Admin/Tickets/Topbar/SortDropdown.tsx
next/web/src/App/Admin/Tickets/index.tsx
next/web/src/api/ticket.ts
next/web/src/utils/types.ts

以选项字段的选项来筛选工单，暂不支持多选，用选项字段筛选时不能同时使用其他字段来筛选，也不能切换排序方式
ctx: https://xindong.slack.com/archives/C01UB1M7BBK/p1675143640272429

feat: search ticket by field option

---

next/api/src/controller/ticket-field.ts
next/api/src/model/TicketField.ts
next/api/src/response/ticket-field.ts
next/web/src/App/Admin/Tickets/Filter/FilterForm/FieldSelect.tsx
next/web/src/api/ticket-field.ts

选项字段值选择现在不会显示没有被表单使用到的字段，还会给停用字段标记“（已停用）”

feat(next): better field select

---

next/api/src/model/User.ts

fix(next/api): verify tds login payload use tds user signing key

---

next/api/src/common/http/error.ts
next/api/src/common/http/index.ts
next/api/src/index.ts
next/api/src/middleware/auth.ts
next/api/src/model/User.ts

https://xindong.slack.com/archives/C0415234S00/p1676088595254959?thread_ts=1675415970.733829&cid=C0415234S00

feat: Error#numCode

---

next/api/src/cloud/ticketStats/slack.ts

fix(next/api): fix slack report with product does not have subcategories

---

next/api/src/cloud/ticketStats/slack.ts

fix(next/api): fix subcategory

---

next/api/src/controller/user.ts
next/api/src/middleware/auth.ts
next/api/src/model/User.ts
next/api/src/utils/jwt.ts

https://xindong.slack.com/archives/C0415234S00/p1676281344390389?thread_ts=1675415970.733829&cid=C0415234S00

feat: EXPIRED_CREDENTIAL error

---

package-lock.json
package.json

更新根目录下面 `leancloud-storage` 的版本至 4.14.0
3.x 到 4.x 应该没有 breaking change？

chore: update leancloud-storage

---

in-app/v1/src/App/Articles/index.tsx
in-app/v1/src/App/Articles/utils.tsx
in-app/v1/src/App/Tickets/index.tsx
in-app/v1/src/App/TopCategories/index.tsx
in-app/v1/src/api/category.ts
in-app/v1/src/components/NewTicketButton/index.tsx
in-app/v1/src/i18n/index.ts
in-app/v1/src/i18n/locales/en.json
in-app/v1/src/i18n/locales/jp.json
in-app/v1/src/i18n/locales/ko.json
in-app/v1/src/i18n/locales/zh.json

feat: in app i18n

---

oauth/xd-cas.js

chore: assign collaborator roles by default for sso users

---

Deploy.md
modules/Ticket/Evaluation.js
modules/Ticket/RecentTickets.js
modules/Ticket/TicketMetadata.js
modules/Ticket/index.css
modules/Ticket/index.js
modules/i18n/locales/zh.json
next/api/src/model/Ticket.ts
next/api/src/response/ticket.ts
next/api/src/router/ticket.ts
next/api/src/ticket/TicketUpdater.ts
resources/schema/Ticket.json

ctx: https://xindong.atlassian.net/wiki/spaces/~631ffa1bcd4a82cf977c6997/pages/619589587

feat: associate ticket

---

next/api/src/model/Group.ts
next/api/src/service/group.ts
next/api/src/ticket/automation/trigger/condition/currentUserId.ts
next/web/src/App/Admin/Settings/Automations/Triggers/conditions/CurrentUserId.tsx
next/web/src/App/Admin/Settings/Automations/components/TriggerForm/CustomField.tsx

feat: [trigger condition] currentUserId.belongsToGroup

---

next/api/src/router/article.ts
next/api/src/ticket-form/ticket-form-note/responses.ts
next/api/src/ticket-form/ticket-form-note/ticket-form-note.controller.ts
next/api/src/ticket-form/ticket-form-note/ticket-form-note.service.ts
next/web/src/App/Admin/Settings/TicketForms/EditTicketForm.tsx
next/web/src/App/Admin/Settings/Topics/index.tsx
next/web/src/App/Tickets/New/TicketForm/index.tsx
next/web/src/api/article.ts
next/web/src/api/ticket-form-note.ts

fix: article and ticket form note

---

in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Input/index.tsx
in-app/v1/src/App/Tickets/New/CustomForm/CustomField/index.tsx
in-app/v1/src/api/ticket-form.ts
in-app/v1/src/i18n/locales/en.json
in-app/v1/src/i18n/locales/jp.json
in-app/v1/src/i18n/locales/ko.json
in-app/v1/src/i18n/locales/zh.json
next/api/src/controller/ticket-field.ts
next/api/src/model/TicketField.ts
next/api/src/response/ticket-field.ts
next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx
next/web/src/App/Admin/Settings/TicketFields/index.tsx
next/web/src/api/ticket-field.ts
resources/schema/TicketField.json

导入 TicketField.json，添加 pattern 列。

feat: use regex to validate a text field

---

next/web/src/App/Admin/Stats/StatsPage.tsx
next/web/src/App/Admin/Stats/StatusPage.tsx
next/web/src/App/Admin/Stats/index.tsx
next/web/src/components/Page/SubMenu/BaseMenu.tsx
next/web/src/components/Page/SubMenu/SiderMenu.tsx
next/web/src/components/Page/SubMenu/index.tsx

- 修复因为之前布局调整导致统计页没有 padding 的问题。
- 重构侧边菜单

refactor(next/web): side menu and statistics pages

---

next/web/package-lock.json
next/web/package.json

升级一下 next/web 用的 vite 版本。v3 到 v4 没啥需要调整的，直接升上去就行。

feat(next/web): upgrade vite to v4.2.1

---

modules/Ticket/TicketMetadata.js
next/api/src/router/ticket.ts

https://github.com/leancloud/ticket/compare/b64d40a63f995dc20a30c0200fe43dcdc95b90de..2e7c7f1a33b6321fbe8567a91dda48989f3f4de9
这次 rebase 给弄没了..

fix(next/api): fix missing language update

---

next/api/src/router/ticket.ts
next/api/src/ticket/automation/condition/language.ts
next/api/src/ticket/automation/context.ts
next/api/src/ticket/automation/time-trigger/condition/index.ts
next/api/src/ticket/automation/trigger/condition/index.ts
next/api/src/ticket/export/ExportTicket.ts
next/api/src/ticket/view/conditions/index.ts
next/api/src/ticket/view/conditions/language.ts
next/api/src/utils/conditions.ts
next/web/src/App/Admin/Settings/Automations/TimeTriggers/conditions/index.ts
next/web/src/App/Admin/Settings/Automations/Triggers/conditions/index.ts
next/web/src/App/Admin/Settings/Automations/conditions/Language.tsx
next/web/src/App/Admin/Settings/Views/EditView.tsx
next/web/src/App/Admin/Settings/Views/components/LanguageSelect.tsx
next/web/src/App/Admin/Settings/Views/conditions.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Filter/useTicketFilter.tsx
next/web/src/App/Admin/Tickets/TicketView/TicketTable/index.tsx
next/web/src/App/Admin/Views/index.tsx
next/web/src/App/Admin/components/LocaleSelect.tsx
next/web/src/api/ticket.ts
next/web/src/i18n/locales.ts

feat: language trigger, view, filter and export

---

next/api/src/router/ticket.ts
next/web/src/App/Admin/Views/index.tsx
next/web/src/api/ticket.ts

由于实现一个功能完备的 popover 是个技术活，这里就仅满足基本需求（悬停展示、不被遮挡）。

feat(next/web):[view] ticket overview

---

in-app/v1/src/App/Tickets/New/CustomForm/CustomField/Input/index.tsx

feat(in-app): input field validate white space

---

in-app/v1/vite.config.js

feat(in-app): add globalThis polyfill to modern bundle

---

modules/Ticket/ReplyCard.js
modules/Ticket/index.js
next/api/src/model/User.ts
next/api/src/router/reply.ts

feat: allow agent update reply created by other agent

---

next/web/src/App/Admin/Settings/Groups/index.tsx

把编辑组员的 multiple select 换成 transfer。客服、组员多的话，用 select 管理起来太痛苦拉

feat(next/web): use transfer to manage group members

---

next/api/src/common/http/error.ts
next/api/src/controller/customer-service.ts

优化报错信息，暂时定个 BadRequest 的 ErrCode 为 9100

perf(api): better error when add an existing customer service to customer service

---

next/api/src/orm/query.ts

修复 Query#getRawCondition 存在向查询条件树中插入新节点的副作用的问题。该问题会导致后续添加新的查询条件时，新条件与所有旧条件为 OR 的关系。

fix(next/api): unexpectedly changed query conditions

---

api/ticketField/fieldService.js
modules/Ticket/TicketMetadata.js
next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx

还在用 `/api/1/ticket-fields?ids=`，本想顺手改到 2 的，发现好像并没有完全对应的实现就在 1 里也加了 meta。

feat(web): sort fields by priority

---

next/api/src/controller/support-email.ts
next/api/src/support-email/entities/SupportEmail.ts
next/api/src/support-email/services/email.ts
next/api/src/support-email/types.ts
next/web/src/App/Admin/Settings/SupportEmails/SupportEmailForm.tsx
next/web/src/api/support-email.ts
resources/schema/SupportEmail.json

客服邮箱支持指定 mailbox。
导入 SupportEmail.json，添加 mailbox 列。

feat(next/api): specify mailbox for support email

---

next/api/src/orm/model.ts

忘记了当时是抄的哪个 ORM 了，加入了一些 hook 但并没有用到。感觉这种强行将逻辑拆开的方式也不是最佳实践，还是去掉罢。

refactor(next/api): [orm] remove create/update hooks

---

api/next-shim.js
api/ticket/api.js
next/api/src/events/index.ts
next/api/src/ticket/TicketCreator.ts
next/api/src/ticket/TicketUpdater.ts

扩展 ticket 事件的上下文，移除 API 1 中相关的部分。

feat(api): extend ticket event

---

next/api/src/router/ticket.ts
next/api/src/ticket/export/ExportTicket.ts
next/api/src/ticket/export/index.ts
next/web/src/App/Admin/Tickets/Topbar/Exporter.tsx
next/web/src/api/ticket.ts

The local time format is more convenient for Excel.
https://xindong.slack.com/archives/C82ANGJP3/p1670397846950929

feat: allow users to choose a time format for exported data

---

api/User.js
api/launch.js
api/next-shim.js
next/api/src/integration/index.ts
next/api/src/launch.ts

在 next 中提供等待某些操作（比如连接 Kafka，获取 Config 表中的配置）完成后再启动应用的能力。

feat: wating for the next app to be ready

---

next/web/src/App/Admin/Tickets/Topbar/index.tsx
next/web/src/App/Admin/Tickets/useTicketSwitchType.tsx

perf(next/web): hide toggle type button when user is not customer service

---

leanengine.yaml

build: remove unnecessary `cd`

---

next/api/src/controller/metrics.ts
next/web/src/App/Admin/Stats/Duration.tsx
next/web/src/api/metrics.ts

feat: duration metrics filters

---

next/api/src/router/ticket.ts

改完后没法删除字段值了，有需要的话等详情页迁完再新弄个接口支持一下罢。

fix(next/api): lost field data outside the current form

---

next/api/src/api-log/crm/crm.service.ts
next/api/src/events/index.ts
next/api/src/integration/taptap-dw/index.ts
next/api/src/ticket/TicketCreator.ts

feat(next/api): taptap data warehouse

---

next/api/src/integration/taptap-dw/index.ts

TicketSnapshot 中添加文件字段的 URL。还加入了 LeanCloud App ID，方便后续区分多个应用 :thinking:

feat(next/api): add file urls to ticket snapshot

---

next/web/src/App/Admin/Sidebar/index.tsx

fix(next/web): remove search from sidebar

---

next/api/src/router/ticket.ts

feat(next/api): allow unset ticket.language

---

next/web/src/App/Admin/Tickets/Ticket/TagForm.tsx
next/web/src/App/Admin/Tickets/Ticket/TicketContext.tsx
next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/index.tsx
next/web/src/App/Admin/Tickets/Ticket/api1.tsx
next/web/src/App/Admin/Tickets/Ticket/components/FormField.tsx
next/web/src/App/Admin/Tickets/Ticket/components/FormLabel.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyEditor.tsx
next/web/src/App/Admin/Tickets/Ticket/lang.ts
next/web/src/api/group.ts
next/web/src/api/ticket.ts
next/web/src/components/common/CustomerServiceSelect.tsx
next/web/src/components/common/GroupSelect.tsx

完成详情页右侧部分，除了关联工单和下一张工单按钮。这俩功能不熟，也不是重度使用的功能。在旧版里排版就有问题，新版要不要放到右侧也要在考虑下，所以就先不管了 🏃

feat(next/web): ticket detail page stage 2

---

next/web/src/App/Admin/Tickets/Ticket/TicketContext.tsx
next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/index.tsx
next/web/src/App/Admin/Tickets/Ticket/components/CategoryCascader.tsx
next/web/src/App/Admin/Tickets/Ticket/components/LeanCloudApp.tsx
next/web/src/leancloud/index.ts

实现了左侧应用按钮和分类，因为应用按钮是摸黑写的，想先合了发上去试试 :eyes:

feat(next/web): ticket detail page stage 2.5

---

.github/workflows/merge-branches.yaml

自动将主分支修改合并到定制的分支下，如果有 conflict 会给 slack 推送消息
配好了

ci: impl auto rebasing workflow

---

next/api/src/response/reply.ts

`GET /api/2/tickets/:id/replies` 返回 reply.internal。

feat(next/api): add reply.internal to response

---

next/api/src/router/article.ts
next/web/src/App/Admin/Settings/Articles/ArticleDetail.tsx

feat(next): delete article translation

---

api/ticket/api.js
modules/Ticket/ReplyCard.js
modules/Ticket/ReplyRevisionsModal.js
modules/Ticket/index.js
next/api/src/model/ReplyRevision.ts
next/api/src/response/reply-revision.ts
next/api/src/router/reply.ts
resources/schema/ReplyRevision.json

临时在旧版详情页里实现查看回复修改记录的功能。实现的比较粗糙，新版里再好好弄一下罢。
导入 ReplyRevision.json，创建 ReplyRevision class。

feat: reply revisions

---

modules/App.js
modules/GlobalNav.js
modules/Settings/index.js
modules/common.js
modules/context/index.js
next/api/scripts/admin-migration.mjs
next/api/src/controller/customer-service.ts
next/api/src/middleware/auth.ts
next/api/src/model/Role.ts
next/api/src/model/User.ts
next/api/src/service/role.ts
next/web/src/App/Admin/Settings/Members/index.tsx
next/web/src/App/Admin/Settings/index.tsx
next/web/src/App/Admin/Sidebar/index.tsx
next/web/src/App/Admin/Views/index.tsx
next/web/src/App/Admin/components/RoleCheckboxGroup.tsx
next/web/src/api/customer-service.ts
next/web/src/components/common/CustomerServiceSelect.tsx
next/web/src/leancloud/index.ts
package-lock.json
package.json

把原来隐藏的 admin 角色暴露出来。限制只有 admin 才能访问配置页面。添加与管理的部分还没有实现。

feat: admin

---

next/api/src/controller/article-topic.ts
next/api/src/controller/category.ts
next/api/src/controller/collaborator.ts
next/api/src/controller/customer-service.ts
next/api/src/controller/dynamic-content.ts
next/api/src/controller/group.ts
next/api/src/controller/metrics.ts
next/api/src/controller/support-email.ts
next/api/src/controller/tag-metadata.ts
next/api/src/controller/ticket-field.ts
next/api/src/controller/view.ts
next/api/src/router/article.ts
next/api/src/router/ticket-stats.ts
next/api/src/router/time-trigger.ts
next/api/src/router/trigger.ts
next/api/src/ticket-form/ticket-form-note/ticket-form-note.controller.ts
next/api/src/ticket-form/ticket-form.controller.ts
next/web/src/App/Admin/Sidebar/index.tsx

工单统计只有管理员能看
还要给前端路由加个权限判断和后端鉴权改成 adminOnly

feat: update admin only api and ui

---

next/web/src/App/Admin/Tickets/Ticket/Timeline/OpsLog.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/ReplyCard.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/Time.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/index.module.css
next/web/src/App/Admin/Tickets/Ticket/Timeline/index.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/useTimeline.ts
next/web/src/App/Admin/Tickets/Ticket/components/CustomFields.tsx
next/web/src/App/Admin/Tickets/Ticket/components/useModal.tsx
next/web/src/api/reply.ts
next/web/src/api/ticket.ts

完整实现「时间线」功能，包括用户回复、客服回复、内部注释和操作日志。
回复框还有一些很细的功能，比如编辑、删除、自动截断、翻译，这些单开个 PR。

feat(next/web): ticket detail page stage 4

---

.github/workflows/merge-branches.yaml

ci: continue when failed to rebase one branch

---

next/web/src/App/Admin/Settings/TicketFields/TicketFieldForm.tsx

perf(next/web): refactor ticket field meta ui

---

.github/workflows/merge-branches.yaml

Fix https://github.com/leancloud/ticket/actions/runs/5184402895/jobs/9343265309

ci: fix dependabot failed to push

---

.github/workflows/deployment.yaml
.github/workflows/matrix_includes.json

ci: impl continuous deployment

---

next/web/src/App/Admin/Tickets/Ticket/components/ReplyEditor.tsx
next/web/src/App/Admin/Tickets/Ticket/components/useModal.tsx
next/web/src/App/Admin/components/Uploader.tsx
next/web/src/api/file.ts

feat(next/web): ticket detail page stage 5.5

---

next/api/src/controller/group.ts
next/api/src/model/Group.ts
next/api/src/response/group.ts
next/web/src/App/Admin/Settings/Groups/index.tsx
next/web/src/App/Admin/Sidebar/index.tsx
next/web/src/api/group.ts
next/web/src/leancloud/index.ts
resources/schema/Group.json

feat: group permission control

---

next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/components/LocaleSelect.tsx

fix(next/web): fix type error

---

modules/Home.js
next/web/src/App/Admin/Sidebar/index.tsx
next/web/src/App/Admin/index.tsx
next/web/src/components/RequirePermission.tsx
next/web/src/leancloud/index.ts

没权限时候显示 fallback，重定向 /next/admin 至第一个拥有权限的页面

feat: better redirect with permissions

---

next/web/src/App/Admin/Tickets/Ticket/mixed-ticket.tsx
next/web/src/App/Admin/Tickets/Ticket/timeline-data.ts
next/web/src/leancloud/index.ts
next/web/src/utils/useCurrentRef.ts

订阅 Ticket、Reply 和 OpsLog。支持实时更新工单和回复，自动获取新回复和操作日志，自动移除被删除的回复。

feat(next/web): ticket detail page stage 5.6

---

next/web/src/App/Admin/Settings/Articles/ArticleDetail.tsx
next/web/src/App/Admin/Settings/Automations/TimeTriggers/index.tsx
next/web/src/App/Admin/Settings/Automations/Triggers/index.tsx
next/web/src/App/Admin/Settings/Categories/index.tsx
next/web/src/App/Admin/Settings/Groups/index.tsx
next/web/src/App/Admin/Settings/Members/index.tsx
next/web/src/App/Admin/Settings/QuickReplies/QuickReplyForm.tsx
next/web/src/App/Admin/Settings/QuickReplies/index.tsx
next/web/src/App/Admin/Settings/Tags/index.tsx
next/web/src/App/Admin/Settings/TicketForms/EditTicketForm.tsx
next/web/src/App/Admin/Settings/TicketForms/index.tsx
next/web/src/App/Admin/Settings/Topics/index.tsx
next/web/src/App/Admin/Settings/Vacations/index.tsx
next/web/src/App/Admin/Settings/Views/index.tsx
next/web/src/App/Admin/Stats/ReplyDetails.tsx
next/web/src/App/Admin/Stats/StatsPage.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/CreatedAtSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/FieldSelect.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Filter/useTicketFilter.tsx
next/web/src/App/Admin/Tickets/Topbar/SortDropdown.tsx
next/web/src/App/Admin/Tickets/index.tsx
next/web/src/App/Admin/Tickets/useTicketSwitchType.tsx
next/web/src/App/Admin/Views/index.tsx
next/web/src/App/Tickets/New/TicketForm/Fields/Upload.tsx
next/web/src/App/Tickets/New/TicketForm/index.tsx
next/web/src/App/Tickets/New/index.tsx
next/web/src/components/Sentry/ErrorBoundary.tsx
next/web/src/components/common/Category.tsx
next/web/src/components/common/CategorySelect.tsx

https://aheadcreative.co.uk/articles/when-to-use-react-usecallback/ :eyes:

refactor(next/web): remove unnecessary useCallback

---

next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/index.tsx
next/web/src/App/Admin/Tickets/Ticket/components/EditReplyModal.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyCard.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyEditor.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyRevisionsModal.tsx
next/web/src/App/Admin/Tickets/Ticket/timeline-data.ts
next/web/src/App/Admin/components/Uploader.tsx
next/web/src/api/reply.ts

新增：
- 修改回复内容
- 展示回复修改记录
- 删除回复

feat(next/web): modify reply

---

next/web/src/App/Admin/Tickets/Ticket/components/ReplyCard.tsx
next/web/src/App/Admin/Tickets/Ticket/components/Time.tsx

至此回复卡片的功能就全都实现了。
感觉 navigator.clipboard.writeText 的支持度很高，再加上不是核心功能，就不用第三方库了。

feat(next/web): copy reply link

---

in-app/v1/src/App/Articles/index.tsx

This change was introduced in 5ea8c7a but overwrited by 151cfc2

fix(in-app): correct paddings

---

next/api/src/orm/model.ts

之前的实现中子类会在 setField 时初始化 this.fields，这么做是为了为了不同 Model 中定义的 fields 相互独立。但这种实现方式会导致父类中定义过字段后，子类定义的字段会污染父类的 fields。relations、onDecodeHooks 也有这个问题。
所以 Category 中定义的字段也会跑到 AliasModel 中去。不过好在目前只有 Category 继承自 AliasModel，所以没有什么影响。
修改后的 Model 支持字段、关系继承且不会污染父类。decode hook 不确定要不要支持继承，就先保证不会污染父类，等有需要的时候再说罢。

feat(next/api): [orm] fields and relations can be inherited

---

next/api/src/ticket/TicketUpdater.ts

fix(next/api): disassociate ticket

---

next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/components/Evaluation.tsx
next/web/src/App/Admin/Tickets/Ticket/components/RecentTickets.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyEditor.tsx
next/web/src/App/Admin/Tickets/Ticket/mixed-ticket.tsx

feat(next/web): ticket detail page stage 7

---

next/web/src/App/Admin/Tickets/Filter/FilterForm/MetadataList.tsx
next/web/src/App/Admin/Tickets/Filter/FilterForm/index.tsx
next/web/src/App/Admin/Tickets/Filter/useTicketFilter.tsx
next/web/src/api/ticket.ts

feat(next/web): search tickets by metadata

---

next/web/src/App/Admin/Stats/Duration.tsx
next/web/src/App/Admin/Tickets/Ticket/components/RecentTickets.tsx
next/web/src/App/Admin/Tickets/TicketTable.tsx
next/web/src/App/Admin/components/TicketLink.tsx
next/web/src/components/common/RecentTickets.tsx

TicketLink 改动：
- nid 挪到标题左侧
- 标题内容支持截断
- 点击 nid 跳转到新版详情页

feat(next/web): ticket link navigation

---

next/api/src/controller/ticket.ts
next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/components/RecentTickets.tsx
next/web/src/App/Admin/components/TicketLink.tsx
next/web/src/api/ticket.ts

feat(next/web): associate/disassociate tickets

---

next/web/src/App/Admin/Tickets/Ticket/TagForm.tsx
next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/index.tsx
next/web/src/App/Admin/Tickets/Ticket/components/OpsLog.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyCard.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyEditor.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyRevisionsModal.tsx
next/web/src/App/Admin/components/UserLabel.tsx

feat(next/web): improve ticket detail page

---

next/api/src/response/reply.ts
next/api/src/router/ticket.ts
next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/Timeline/index.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyCard.tsx
next/web/src/App/Admin/Tickets/Ticket/components/ReplyRevisionsModal.tsx
next/web/src/App/Admin/Tickets/Ticket/timeline-data.ts
next/web/src/api/reply.ts
next/web/src/api/ticket.ts

feat(next/web): display deleted replies

---

next/api/src/integration/jira.ts
next/api/src/model/Ticket.ts
next/web/src/App/Admin/Views/index.tsx
next/web/src/App/Admin/components/TicketLink.tsx

feat: new ticket page

---

next/api/src/model/User.ts

ctx.state.currentUser must include sessionToken.
fix https://xindong.atlassian.net/browse/TDS-3919

fix(api/auth): ensure sessionToken for TDSUsers

---

next/api/src/service/openai.ts
package-lock.json
package.json

fix(next/api): fix proxy econnreset

---

next/web/src/App/Admin/Tickets/Ticket/timeline-data.ts

修复多次获取更多回复、操作日志时丢失 pageParam，相当于在已有数据的基础上从头开始获取。

fix(next/web): fetch more timeline items

---

modules/Ticket/ReplyRevisionsModal.js
next/api/src/model/ReplyRevision.ts
next/api/src/router/reply.ts
next/web/src/App/Admin/Tickets/Ticket/components/ReplyRevisionsModal.tsx
next/web/src/api/reply.ts

feat: reply deletion record

---

next/api/src/middleware/auth.ts
next/api/src/model/User.ts
next/api/src/orm/model.ts

https://xindong.slack.com/archives/C01RY5JHB47/p1689682687715969

feat(next/api): tds user cache encoding

---

in-app/v1/src/App/Tickets/Ticket/index.tsx

fix https://xindong.atlassian.net/browse/TDS-3951
这个 bug /tickets 页拆分两个 tab 导致的。

fix(in-app): try all keys when resetting cached unread count

---

next/api/src/controller/category.ts

这个选项感觉没有理由「必填」，不知道是不是有什么特殊的考量？ @fareco

fix(api): isTicketEnabled should be optional

---

next/api/src/controller/verification.ts
next/web/src/App/Admin/Tickets/Ticket/components/RecentTickets.tsx
next/web/src/App/Admin/Verification/index.tsx
next/web/src/App/Admin/components/TicketLink.tsx
next/web/src/App/Admin/index.tsx

feat: agent verification

---

next/api/src/controller/group.ts
next/api/src/controller/ticket.ts
next/api/src/controller/user.ts

allow staffs to view ticket details normally.

fix(api): use more masterKey

---

next/web/package-lock.json
next/web/package.json
next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/api1.tsx
next/web/src/App/Admin/Tickets/Ticket/components/CustomFields.tsx
next/web/src/api/ticket.ts

feat(web): port field preview template

---

next/api/package-lock.json
next/api/package.json
next/api/src/service/openai.ts

修复 AI 分类失败的问题，添加了环境变量 `OPENAI_MODEL` 来配置 AI 分类使用的模型（默认 `gpt-3.5-turbo`）

fix: ai classify failed

---

next/api/src/service/openai.ts

perf(next/api): use OPENAI_PROXY instead of http_proxy

---

next/api/src/controller/ticket.ts
next/web/src/App/Admin/Tickets/Ticket/TicketDetail.tsx
next/web/src/App/Admin/Tickets/Ticket/components/TicketViewers.tsx
next/web/src/App/Admin/Tickets/Ticket/hooks/useTicketViewers.ts

feat(next/web): display ticket viewers

---

next/api/src/controller/article-topic.ts
next/api/src/model/ArticleTopic.ts
next/api/src/response/article-topic.ts
next/web/src/App/Admin/Settings/Topics/index.tsx
next/web/src/api/topic.ts
resources/schema/FAQTopic.json

feat: topic comment

---

in-app/v1/src/App/Home/AiClassify.tsx
in-app/v1/src/App/Home/Notices.tsx
in-app/v1/src/App/index.tsx
in-app/v1/src/index.css

修复公告、AI 分类样式错乱问题，优化下安卓曲面屏显示。
设计已经验收过了。

fix: styles
